import type { SceneConfig, SceneType } from '@/types'

export const SCENE_CONFIGS: Record<SceneType, SceneConfig> = {
  windTunnel: {
    type: 'windTunnel',
    name: '风洞实验',
    description: '模拟气流穿过障碍物的空气动力学效果',
    icon: 'Wind',
    backgroundColor: '#0A1628',
    fluidParams: {
      density: 0.8,
      viscosity: 0.05,
      velocity: 12,
      diffusion: 0.0005,
      vorticityScale: 0.2,
      velocityDissipation: 0.998,
      pressureIterations: 30,
      transparency: 0.85,
    },
    emitters: [
      {
        id: 'wind-left',
        position: { x: 20, y: 128 },
        direction: { x: 1, y: 0 },
        rate: 0.5,
        color: { r: 0, g: 0.96, b: 1 },
        enabled: true,
      },
    ],
    forceFields: [
      {
        id: 'wind-force',
        position: { x: 50, y: 128 },
        direction: { x: 1, y: 0 },
        strength: 15,
        radius: 200,
        enabled: true,
      },
    ],
    colorZones: [
      {
        id: 'zone-left',
        position: { x: 60, y: 128 },
        radius: 40,
        color: { r: 0, g: 0.6, b: 1 },
        enabled: true,
      },
      {
        id: 'zone-right',
        position: { x: 200, y: 128 },
        radius: 50,
        color: { r: 0, g: 1, b: 0.8 },
        enabled: true,
      },
    ],
  },

  river: {
    type: 'river',
    name: '河流模拟',
    description: '模拟水流流动和漩涡效果',
    icon: 'Waves',
    backgroundColor: '#0A1628',
    fluidParams: {
      density: 1.5,
      viscosity: 0.08,
      velocity: 6,
      diffusion: 0.001,
      vorticityScale: 0.12,
      velocityDissipation: 0.995,
      pressureIterations: 25,
      transparency: 0.75,
    },
    emitters: [
      {
        id: 'river-top',
        position: { x: 128, y: 20 },
        direction: { x: 0, y: 1 },
        rate: 0.6,
        color: { r: 0, g: 0.4, b: 1 },
        enabled: true,
      },
    ],
    forceFields: [
      {
        id: 'gravity',
        position: { x: 128, y: 128 },
        direction: { x: 0, y: 1 },
        strength: 8,
        radius: 300,
        enabled: true,
      },
    ],
    colorZones: [
      {
        id: 'shallow',
        position: { x: 128, y: 60 },
        radius: 60,
        color: { r: 0.2, g: 0.8, b: 1 },
        enabled: true,
      },
      {
        id: 'deep',
        position: { x: 128, y: 200 },
        radius: 80,
        color: { r: 0, g: 0.2, b: 0.7 },
        enabled: true,
      },
      {
        id: 'foam',
        position: { x: 128, y: 128 },
        radius: 30,
        color: { r: 0.9, g: 0.95, b: 1 },
        enabled: true,
      },
    ],
  },

  smoke: {
    type: 'smoke',
    name: '烟雾缭绕',
    description: '模拟烟雾上升和扩散的飘逸效果',
    icon: 'Cloud',
    backgroundColor: '#0A1628',
    fluidParams: {
      density: 0.6,
      viscosity: 0.15,
      velocity: 3,
      diffusion: 0.003,
      vorticityScale: 0.08,
      velocityDissipation: 0.99,
      pressureIterations: 20,
      transparency: 0.6,
    },
    emitters: [
      {
        id: 'smoke-center',
        position: { x: 128, y: 230 },
        direction: { x: 0, y: -1 },
        rate: 0.4,
        color: { r: 0.6, g: 0.6, b: 0.7 },
        enabled: true,
      },
      {
        id: 'smoke-left',
        position: { x: 80, y: 230 },
        direction: { x: 0.2, y: -1 },
        rate: 0.3,
        color: { r: 0.5, g: 0.4, b: 0.6 },
        enabled: true,
      },
      {
        id: 'smoke-right',
        position: { x: 176, y: 230 },
        direction: { x: -0.2, y: -1 },
        rate: 0.3,
        color: { r: 0.7, g: 0.5, b: 0.5 },
        enabled: true,
      },
    ],
    forceFields: [
      {
        id: 'buoyancy',
        position: { x: 128, y: 128 },
        direction: { x: 0, y: -1 },
        strength: 6,
        radius: 300,
        enabled: true,
      },
      {
        id: 'turbulence',
        position: { x: 128, y: 100 },
        direction: { x: 0.5, y: 0 },
        strength: 3,
        radius: 100,
        enabled: true,
      },
    ],
    colorZones: [
      {
        id: 'warm',
        position: { x: 128, y: 200 },
        radius: 50,
        color: { r: 1, g: 0.5, b: 0.2 },
        enabled: true,
      },
      {
        id: 'cool',
        position: { x: 128, y: 80 },
        radius: 60,
        color: { r: 0.4, g: 0.4, b: 0.6 },
        enabled: true,
      },
    ],
  },

  custom: {
    type: 'custom',
    name: '自由创作',
    description: '自定义参数，自由探索流体效果',
    icon: 'Settings',
    backgroundColor: '#0A1628',
    fluidParams: {
      density: 1.0,
      viscosity: 0.1,
      velocity: 5,
      diffusion: 0.001,
      vorticityScale: 0.15,
      velocityDissipation: 0.995,
      pressureIterations: 25,
      transparency: 0.7,
    },
    emitters: [],
    forceFields: [],
    colorZones: [],
  },
}
