package com.sla.monitor.controller;

import com.sla.monitor.model.RootCauseAnalysis;
import com.sla.monitor.model.RootCauseRule;
import com.sla.monitor.repository.RootCauseRuleRepository;
import com.sla.monitor.service.RootCauseRuleMiningService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/root-cause-rules")
public class RootCauseRuleController {

    private final RootCauseRuleRepository ruleRepository;
    private final RootCauseRuleMiningService ruleMiningService;

    public RootCauseRuleController(RootCauseRuleRepository ruleRepository,
                                    RootCauseRuleMiningService ruleMiningService) {
        this.ruleRepository = ruleRepository;
        this.ruleMiningService = ruleMiningService;
    }

    @GetMapping
    public List<RootCauseRule> getAllRules(
            @RequestParam(required = false) Boolean active,
            @RequestParam(required = false) Boolean autoGenerated,
            @RequestParam(required = false) RootCauseAnalysis.RootCauseCategory causeType) {
        
        if (causeType != null) {
            return ruleRepository.findByRootCauseTypeAndActiveTrue(causeType);
        }
        if (Boolean.TRUE.equals(autoGenerated)) {
            return ruleRepository.findAutoGeneratedRules();
        }
        if (Boolean.TRUE.equals(active)) {
            return ruleRepository.findByActiveTrueOrderByConfidenceScoreDesc();
        }
        return ruleRepository.findAll();
    }

    @GetMapping("/{id}")
    public ResponseEntity<RootCauseRule> getRuleById(@PathVariable Long id) {
        return ruleRepository.findById(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/code/{code}")
    public ResponseEntity<RootCauseRule> getRuleByCode(@PathVariable String code) {
        return ruleRepository.findByRuleCode(code)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/match")
    public List<RootCauseRule> matchRules(
            @RequestParam(required = false) Double availability,
            @RequestParam(required = false) Double latency,
            @RequestParam(required = false) Double errorRate) {
        return ruleMiningService.matchRules(availability, latency, errorRate);
    }

    @PostMapping
    public ResponseEntity<RootCauseRule> createRule(@RequestBody RootCauseRule rule) {
        if (ruleRepository.existsByRuleCode(rule.getRuleCode())) {
            return ResponseEntity.badRequest().build();
        }
        rule.setAutoGenerated(false);
        RootCauseRule saved = ruleRepository.save(rule);
        return ResponseEntity.ok(saved);
    }

    @PutMapping("/{id}")
    public ResponseEntity<RootCauseRule> updateRule(
            @PathVariable Long id,
            @RequestBody RootCauseRule rule) {
        return ruleRepository.findById(id)
                .map(existing -> {
                    existing.setRuleName(rule.getRuleName());
                    existing.setDescription(rule.getDescription());
                    existing.setRootCauseType(rule.getRootCauseType());
                    existing.setMinAvailabilityThreshold(rule.getMinAvailabilityThreshold());
                    existing.setMaxAvailabilityThreshold(rule.getMaxAvailabilityThreshold());
                    existing.setMinLatencyThreshold(rule.getMinLatencyThreshold());
                    existing.setMaxLatencyThreshold(rule.getMaxLatencyThreshold());
                    existing.setMinErrorRateThreshold(rule.getMinErrorRateThreshold());
                    existing.setMaxErrorRateThreshold(rule.getMaxErrorRateThreshold());
                    existing.setConfidenceScore(rule.getConfidenceScore());
                    existing.setContributingFactors(rule.getContributingFactors());
                    existing.setRecommendations(rule.getRecommendations());
                    existing.setActive(rule.isActive());
                    return ResponseEntity.ok(ruleRepository.save(existing));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRule(@PathVariable Long id) {
        return ruleRepository.findById(id)
                .map(rule -> {
                    ruleRepository.delete(rule);
                    return ResponseEntity.ok().<Void>build();
                })
                .orElse(ResponseEntity.notFound().build());
    }

    @PostMapping("/mine")
    public ResponseEntity<Map<String, Object>> triggerMining() {
        int newRules = ruleMiningService.mineRulesFromHistoricalData();
        Map<String, Object> result = new HashMap<>();
        result.put("newRulesMined", newRules);
        result.put("totalRules", ruleRepository.count());
        result.put("message", "Rule mining completed");
        return ResponseEntity.ok(result);
    }

    @PostMapping("/update-statistics")
    public ResponseEntity<String> updateStatistics() {
        ruleMiningService.updateRuleStatistics();
        return ResponseEntity.ok("Rule statistics updated");
    }

    @GetMapping("/statistics")
    public ResponseEntity<Map<String, Object>> getStatistics() {
        Map<String, Object> stats = new HashMap<>();
        stats.put("totalRules", ruleRepository.count());
        stats.put("activeRules", ruleRepository.findByActiveTrue().size());
        stats.put("autoGeneratedRules", ruleRepository.findAutoGeneratedRules().size());
        
        List<Object[]> rulesByType = ruleRepository.countRulesByType();
        Map<String, Long> typeCounts = new HashMap<>();
        for (Object[] row : rulesByType) {
            typeCounts.put(((RootCauseAnalysis.RootCauseCategory) row[0]).name(), (Long) row[1]);
        }
        stats.put("rulesByType", typeCounts);
        
        return ResponseEntity.ok(stats);
    }
}
