import os
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from collections import defaultdict

from git import Repo, GitCommandError

from git_scanner import LargeFileInfo
from file_analyzer import FileTypeAnalyzer
from bfg_advisor import format_size
from trend_analysis import ChartGenerator, CleanupComparison, TrendAnalyzer


class PRGenerator:
    def __init__(self, repo_path: str, large_files: Dict[str, LargeFileInfo], scanner=None):
        self.repo_path = os.path.abspath(repo_path)
        self.repo = Repo(self.repo_path)
        self.large_files = large_files
        self.scanner = scanner
        self.file_analyzer = FileTypeAnalyzer()

    def generate_branch_name(self) -> str:
        timestamp = datetime.now().strftime("%Y%m%d")
        return f"cleanup/large-files-{timestamp}"

    def generate_gitignore_entries(self) -> List[str]:
        entries = [
            "# === Auto-generated by Git Large Files Detector ===",
            "# Large files detected in repository history",
            ""
        ]

        by_type = defaultdict(list)
        for file_path, info in self.large_files.items():
            file_type = info.file_type.split('/')[0] if '/' in info.file_type else info.file_type
            by_type[file_type].append(file_path)

        for file_type in sorted(by_type.keys()):
            files = by_type[file_type]
            entries.append(f"# {file_type.upper()} files ({len(files)} files)")

            exts = set()
            for f in files:
                ext = FileTypeAnalyzer.get_file_extension(f)
                if ext:
                    exts.add(ext)

            for ext in sorted(exts):
                entries.append(f"*{ext}")

            dirs = set()
            for f in files:
                dirname = os.path.dirname(f)
                if dirname and dirname != '.':
                    dirs.add(dirname)

            if dirs:
                entries.append("")
                entries.append("# Directories containing large files:")
                for d in sorted(dirs):
                    entries.append(f"# {d}/")

            entries.append("")

        return entries

    def generate_pr_title(self) -> str:
        count = len(self.large_files)
        total_size = sum(info.max_size for info in self.large_files.values())
        return f"Cleanup: Remove {count} large files ({format_size(total_size)}) from git history"

    def generate_pr_body(
        self,
        include_charts: bool = True,
        include_details: bool = True
    ) -> str:
        lines = []
        count = len(self.large_files)
        total_size = sum(info.max_size for info in self.large_files.values())

        lines.append("## 📋 Summary")
        lines.append("")
        lines.append(f"This PR removes **{count} large files** ({format_size(total_size)}) "
                     "from the git repository history to reduce repository size.")
        lines.append("")

        if include_charts and self.scanner:
            comparison = CleanupComparison(self.scanner)
            current = comparison.get_current_state()
            after = comparison.get_estimated_after()

            lines.append("## 📊 Impact Analysis")
            lines.append("")
            lines.append("### Repository Size Reduction")
            lines.append("")
            lines.append("```")
            chart_lines = ChartGenerator.generate_size_chart(
                current['total_repo_size'],
                after['estimated_repo_size'],
                ''
            )
            lines.extend(chart_lines[2:])
            lines.append("```")
            lines.append("")

            if self.scanner:
                trend = TrendAnalyzer(self.scanner)
                trend.analyze_by_commit()
                summary = trend.get_summary()
                if summary:
                    lines.append("### Large Files Trend")
                    lines.append("")
                    lines.append(f"- **Growth period**: {summary['start_date'].strftime('%Y-%m-%d')} to {summary['end_date'].strftime('%Y-%m-%d')}")
                    lines.append(f"- **File count growth**: {summary['initial_count']} → {summary['final_count']} (+{summary['count_growth']})")
                    lines.append(f"- **Size growth**: {format_size(summary['initial_size'])} → {format_size(summary['final_size'])} (+{format_size(summary['size_growth'])})")
                    lines.append("")

        lines.append("## 🗂  Files To Be Removed")
        lines.append("")

        by_type = defaultdict(list)
        for file_path, info in self.large_files.items():
            file_type = info.file_type.split('/')[0] if '/' in info.file_type else info.file_type
            by_type[file_type].append((file_path, info))

        for file_type in sorted(by_type.keys()):
            files = by_type[file_type]
            type_size = sum(info.max_size for _, info in files)
            lines.append(f"### {file_type.upper()} ({len(files)} files, {format_size(type_size)})")
            lines.append("")

            if include_details:
                lines.append("| File | Size | First Seen | Last Modified | Commits |")
                lines.append("|------|------|------------|---------------|---------|")
                for file_path, info in sorted(files, key=lambda x: -x[1].max_size):
                    lines.append(
                        f"| `{file_path}` | {format_size(info.max_size)} | "
                        f"{info.first_introduced.strftime('%Y-%m-%d')} | "
                        f"{info.last_modified.strftime('%Y-%m-%d')} | "
                        f"{info.commit_count} |"
                    )
            else:
                for file_path, info in sorted(files, key=lambda x: -x[1].max_size)[:10]:
                    lines.append(f"- `{file_path}` ({format_size(info.max_size)})")
                if len(files) > 10:
                    lines.append(f"- ... and {len(files) - 10} more files")
            lines.append("")

        lines.append("## 🔧 Cleanup Procedure")
        lines.append("")
        lines.append("This cleanup will be performed using **BFG Repo-Cleaner**:")
        lines.append("")
        lines.append("```bash")
        lines.append("# Clone bare repository")
        lines.append(f"git clone --mirror {self.repo_path} repo-clean.git")
        lines.append("")
        lines.append("# Run BFG to remove large files")
        for file_path, info in sorted(self.large_files.items(), key=lambda x: -x[1].max_size)[:5]:
            filename = os.path.basename(file_path)
            lines.append(f"java -jar bfg.jar --delete-files '{filename}' repo-clean.git")
        lines.append("")
        lines.append("# Cleanup and garbage collect")
        lines.append("cd repo-clean.git")
        lines.append("git reflog expire --expire=now --all")
        lines.append("git gc --prune=now --aggressive")
        lines.append("")
        lines.append("# Push cleaned history")
        lines.append("git push --force")
        lines.append("```")
        lines.append("")

        lines.append("## ⚠️ Important Notes")
        lines.append("")
        lines.append("- [ ] All team members have been notified about the history rewrite")
        lines.append("- [ ] All open branches have been considered")
        lines.append("- [ ] All tags have been reviewed")
        lines.append("- [ ] A backup of the original repository exists")
        lines.append("- [ ] CI/CD pipelines have been updated if needed")
        lines.append("- [ ] `.gitignore` has been updated to prevent large files from being re-added")
        lines.append("")

        lines.append("## 📝 .gitignore Suggestions")
        lines.append("")
        lines.append("Add these entries to `.gitignore` to prevent similar large files:")
        lines.append("")
        lines.append("```gitignore")
        lines.extend(self.generate_gitignore_entries())
        lines.append("```")
        lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("*Generated by Git Large Files Detector on "
                     f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

        return '\n'.join(lines)

    def create_cleanup_branch(
        self,
        update_gitignore: bool = True,
        add_pr_body: bool = True,
        branch_name: Optional[str] = None
    ) -> dict:
        result = {
            'success': False,
            'branch_name': branch_name or self.generate_branch_name(),
            'gitignore_updated': False,
            'pr_body_generated': False,
            'pr_body_path': None,
            'warnings': [],
            'error': None
        }

        try:
            current_branch = self.repo.active_branch.name
        except (TypeError, AttributeError):
            current_branch = 'main'

        try:
            branch_name = result['branch_name']
            if branch_name in [b.name for b in self.repo.branches]:
                result['warnings'].append(f"Branch '{branch_name}' already exists")
            else:
                new_branch = self.repo.create_head(branch_name)
                new_branch.checkout()

            if update_gitignore:
                gitignore_path = os.path.join(self.repo_path, '.gitignore')
                existing_entries = set()
                if os.path.exists(gitignore_path):
                    with open(gitignore_path, 'r', encoding='utf-8') as f:
                        existing_entries = set(line.strip() for line in f if line.strip())

                new_entries = self.generate_gitignore_entries()
                entries_to_add = [e for e in new_entries if e not in existing_entries and e and not e.startswith('#')]

                if entries_to_add:
                    with open(gitignore_path, 'a', encoding='utf-8') as f:
                        f.write('\n' + '\n'.join(entries_to_add) + '\n')
                    self.repo.index.add(['.gitignore'])
                    self.repo.index.commit(f"chore: update .gitignore to exclude large files\n\nAdd patterns for large file types detected in history.")
                    result['gitignore_updated'] = True

            if add_pr_body:
                pr_body = self.generate_pr_body()
                pr_dir = os.path.join(self.repo_path, '.git', 'large-files-cleanup')
                os.makedirs(pr_dir, exist_ok=True)
                pr_path = os.path.join(pr_dir, f'PR-{branch_name}.md')
                with open(pr_path, 'w', encoding='utf-8') as f:
                    f.write(f"# {self.generate_pr_title()}\n\n{pr_body}")
                result['pr_body_path'] = pr_path
                result['pr_body_generated'] = True

            try:
                self.repo.git.checkout(current_branch)
            except GitCommandError:
                pass

            result['success'] = True

        except GitCommandError as e:
            result['error'] = f"Git error: {str(e)}"
        except Exception as e:
            result['error'] = str(e)

        return result

    def save_pr_template(self, output_path: Optional[str] = None) -> str:
        if output_path is None:
            output_dir = os.path.join(self.repo_path, '.git', 'large-files-cleanup')
            os.makedirs(output_dir, exist_ok=True)
            output_path = os.path.join(output_dir, f'PR-{self.generate_branch_name()}.md')

        pr_content = f"# {self.generate_pr_title()}\n\n{self.generate_pr_body()}"

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(pr_content)

        return output_path
