import React, { useState, useEffect } from 'react';
import useMeetingMinutes from '../hooks/useMeetingMinutes';
import { 
  CloseIcon, 
  DownloadIcon, 
  CopyIcon, 
  DocumentIcon, 
  RefreshIcon,
  CheckIcon,
  AlertIcon
} from './icons';

const MinutesPanel = ({ onClose }) => {
  const {
    generateMinutes,
    getMinutesStats,
    listMinutes,
    downloadMinutes,
    copyToClipboard,
    isGenerating,
    currentMinutes,
    minutesStats,
    error
  } = useMeetingMinutes();

  const [historyMinutes, setHistoryMinutes] = useState([]);
  const [selectedMinutes, setSelectedMinutes] = useState(null);
  const [tab, setTab] = useState('current');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    loadHistory();
    getMinutesStats();
  }, []);

  const loadHistory = async () => {
    const data = await listMinutes();
    setHistoryMinutes(data);
  };

  const handleGenerate = async () => {
    const result = await generateMinutes();
    if (result.success) {
      setSelectedMinutes(null);
      loadHistory();
    }
  };

  const handleCopy = async () => {
    const summary = selectedMinutes || currentMinutes;
    if (!summary) return;
    
    const success = await copyToClipboard(summary);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = (filename) => {
    downloadMinutes(filename);
  };

  const renderSummary = (summary, filename = null) => {
    if (!summary) return null;

    const priorityColors = {
      high: 'bg-red-500/20 text-red-400',
      medium: 'bg-yellow-500/20 text-yellow-400',
      low: 'bg-green-500/20 text-green-400'
    };

    return (
      <div className="space-y-6">
        <div>
          <h3 className="text-xl font-bold text-white mb-2">{summary.title}</h3>
          {summary.autoGenerated && (
            <div className="flex items-center gap-2 text-sm text-slate-400 mb-4">
              <AlertIcon className="w-4 h-4" />
              <span>本纪要由AI自动生成，仅供参考</span>
            </div>
          )}
        </div>

        {summary.overallSummary && (
          <div>
            <h4 className="text-sm font-semibold text-slate-300 mb-2 flex items-center gap-2">
              <DocumentIcon className="w-4 h-4" />
              会议概述
            </h4>
            <p className="text-slate-200 bg-slate-800/50 p-3 rounded-lg">
              {summary.overallSummary}
            </p>
          </div>
        )}

        {summary.keyPoints?.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-slate-300 mb-2">核心讨论要点</h4>
            <ul className="space-y-2">
              {summary.keyPoints.map((point, i) => (
                <li key={i} className="flex items-start gap-3 text-slate-200">
                  <span className="w-6 h-6 rounded-full bg-primary-500/20 text-primary-400 flex items-center justify-center text-xs font-bold flex-shrink-0">
                    {i + 1}
                  </span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {summary.decisions?.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-slate-300 mb-2">会议决议</h4>
            <div className="space-y-2">
              {summary.decisions.map((decision, i) => (
                <div key={i} className="flex items-start gap-3 text-slate-200 bg-green-500/10 p-3 rounded-lg border border-green-500/20">
                  <CheckIcon className="w-5 h-5 text-green-400 flex-shrink-0 mt-0.5" />
                  <span>{decision}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {summary.actionItems?.length > 0 && (
          <div>
            <h4 className="text-sm font-semibold text-slate-300 mb-2">待办事项</h4>
            <div className="space-y-2">
              {summary.actionItems.map((item, i) => (
                <div key={i} className="bg-slate-800/50 p-3 rounded-lg">
                  <div className="flex items-start justify-between gap-4">
                    <span className="text-slate-200 flex-1">{item.content}</span>
                    <span className={`px-2 py-0.5 rounded text-xs font-medium flex-shrink-0 ${priorityColors[item.priority] || priorityColors.medium}`}>
                      {item.priority === 'high' ? '高优' : item.priority === 'low' ? '低优' : '中优'}
                    </span>
                  </div>
                  <div className="mt-2 text-sm text-slate-400">
                    负责人：{item.assignee}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {summary.nextMeeting && (
          <div>
            <h4 className="text-sm font-semibold text-slate-300 mb-2">下次会议建议</h4>
            <p className="text-slate-200 bg-blue-500/10 p-3 rounded-lg border border-blue-500/20">
              {summary.nextMeeting}
            </p>
          </div>
        )}

        <div className="flex gap-2 pt-4 border-t border-slate-700">
          <button
            onClick={handleCopy}
            className="flex-1 flex items-center justify-center gap-2 bg-slate-700 hover:bg-slate-600 text-white py-2 px-4 rounded-lg transition-colors"
          >
            {copied ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
            {copied ? '已复制' : '复制'}
          </button>
          {filename && (
            <button
              onClick={() => handleDownload(filename)}
              className="flex-1 flex items-center justify-center gap-2 bg-primary-500 hover:bg-primary-600 text-white py-2 px-4 rounded-lg transition-colors"
            >
              <DownloadIcon className="w-4 h-4" />
              下载 Markdown
            </button>
          )}
        </div>
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col bg-slate-800">
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700">
        <h2 className="text-lg font-semibold text-white">会议纪要</h2>
        <button
          onClick={onClose}
          className="w-8 h-8 rounded-lg hover:bg-slate-700 flex items-center justify-center text-slate-400 hover:text-white transition-colors"
        >
          <CloseIcon className="w-5 h-5" />
        </button>
      </div>

      <div className="flex border-b border-slate-700">
        <button
          onClick={() => { setTab('current'); setSelectedMinutes(null); }}
          className={`flex-1 py-3 text-sm font-medium transition-colors ${
            tab === 'current'
              ? 'text-primary-400 border-b-2 border-primary-400'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          当前会议
        </button>
        <button
          onClick={() => { setTab('history'); loadHistory(); }}
          className={`flex-1 py-3 text-sm font-medium transition-colors ${
            tab === 'history'
              ? 'text-primary-400 border-b-2 border-primary-400'
              : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          历史纪要
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4">
        {error && (
          <div className="bg-red-500/20 border border-red-500/30 text-red-400 p-3 rounded-lg mb-4">
            {error}
          </div>
        )}

        {tab === 'current' ? (
          <div>
            {minutesStats && (
              <div className="grid grid-cols-3 gap-2 mb-4">
                <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                  <div className="text-2xl font-bold text-white">{minutesStats.messageCount}</div>
                  <div className="text-xs text-slate-400">消息数</div>
                </div>
                <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                  <div className="text-2xl font-bold text-white">{minutesStats.topicCount}</div>
                  <div className="text-xs text-slate-400">议题数</div>
                </div>
                <div className="bg-slate-700/50 p-3 rounded-lg text-center">
                  <div className="text-2xl font-bold text-white">{minutesStats.actionItemCount}</div>
                  <div className="text-xs text-slate-400">待办数</div>
                </div>
              </div>
            )}

            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-full flex items-center justify-center gap-2 bg-primary-500 hover:bg-primary-600 disabled:bg-slate-600 text-white py-3 px-4 rounded-lg transition-colors mb-4"
            >
              {isGenerating ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  正在生成...
                </>
              ) : (
                <>
                  <RefreshIcon className="w-4 h-4" />
                  生成会议纪要
                </>
              )}
            </button>

            {currentMinutes && !selectedMinutes && (
              <div className="bg-slate-700/30 rounded-lg p-4">
                {renderSummary(currentMinutes)}
              </div>
            )}

            {!currentMinutes && !isGenerating && (
              <div className="text-center py-12 text-slate-400">
                <DocumentIcon className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p>点击上方按钮生成会议纪要</p>
                <p className="text-sm mt-2">系统将自动识别议题、决议和待办事项</p>
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-2">
            {historyMinutes.length === 0 ? (
              <div className="text-center py-12 text-slate-400">
                <DocumentIcon className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p>暂无历史会议纪要</p>
              </div>
            ) : (
              historyMinutes.map((item) => (
                <div
                  key={item.filename}
                  className={`p-4 rounded-lg cursor-pointer transition-colors ${
                    selectedMinutes?.filename === item.filename
                      ? 'bg-primary-500/20 border border-primary-500/30'
                      : 'bg-slate-700/30 hover:bg-slate-700/50 border border-transparent'
                  }`}
                  onClick={() => setSelectedMinutes(item)}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h4 className="text-white font-medium">{item.title}</h4>
                      <div className="text-sm text-slate-400 mt-1">
                        {new Date(item.startTime).toLocaleString('zh-CN')}
                      </div>
                      <div className="flex items-center gap-4 mt-2 text-xs text-slate-400">
                        <span>{item.participantCount} 人参会</span>
                        {item.hasSummary && (
                          <span className={`${item.autoGenerated ? 'text-yellow-400' : 'text-green-400'}`}>
                            {item.autoGenerated ? 'AI生成' : '完整纪要'}
                          </span>
                        )}
                      </div>
                    </div>
                    <div className="flex gap-1">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDownload(item.filename);
                        }}
                        className="p-2 hover:bg-slate-600 rounded-lg transition-colors"
                      >
                        <DownloadIcon className="w-4 h-4 text-slate-400" />
                      </button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        )}

        {selectedMinutes && (
          <div className="mt-4 bg-slate-700/30 rounded-lg p-4">
            {renderSummary(selectedMinutes.summary, selectedMinutes.filename)}
          </div>
        )}
      </div>
    </div>
  );
};

export default MinutesPanel;
