FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o alert-tester ./cmd/platform

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/alert-tester .

EXPOSE 8080

CMD ["./alert-tester"]
