[web_servers]
web01.example.com ansible_user=admin ansible_become=true
web02.example.com ansible_user=admin ansible_become=true
web03.example.com ansible_user=admin ansible_become=true

[db_servers]
db01.example.com ansible_user=centos ansible_become=true
db02.example.com ansible_user=centos ansible_become=true

[app_servers]
app01.example.com ansible_user=ubuntu ansible_become=true
app02.example.com ansible_user=ubuntu ansible_become=true

[all:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[security:children]
web_servers
db_servers
app_servers
