filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
    fields:
      log_type: nginx

output.kafka:
  hosts: ["kafka:29092"]
  topic: "nginx-logs"
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
