package com.schemaregistry.service;

import com.schemaregistry.model.AuditLog;
import com.schemaregistry.repository.AuditLogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class AuditService {

    private final AuditLogRepository auditLogRepository;

    @Autowired
    public AuditService(AuditLogRepository auditLogRepository) {
        this.auditLogRepository = auditLogRepository;
    }

    @Transactional
    public AuditLog logAuditEvent(AuditLog.AuditAction action, String subject, Integer version,
                                  String oldSchema, String newSchema, String description,
                                  String username, Boolean compatibilityPassed, Boolean autoGenerated) {
        AuditLog log = AuditLog.builder()
                .action(action)
                .subject(subject)
                .version(version)
                .oldSchemaText(oldSchema)
                .newSchemaText(newSchema)
                .changeDescription(description)
                .username(username != null ? username : "system")
                .compatibilityCheckPassed(compatibilityPassed)
                .autoGenerated(autoGenerated != null ? autoGenerated : false)
                .build();

        return auditLogRepository.save(log);
    }

    @Transactional
    public AuditLog logSchemaCreated(String subject, String schema, String username) {
        return logAuditEvent(AuditLog.AuditAction.CREATED, subject, 1,
                null, schema, "Schema created", username, null, false);
    }

    @Transactional
    public AuditLog logVersionAdded(String subject, Integer version, String oldSchema,
                                    String newSchema, String username, boolean compatibilityPassed) {
        return logAuditEvent(AuditLog.AuditAction.VERSION_ADDED, subject, version,
                oldSchema, newSchema, "New version added", username, compatibilityPassed, false);
    }

    @Transactional
    public AuditLog logVersionAutoGenerated(String subject, Integer version, String oldSchema,
                                            String newSchema, String description) {
        return logAuditEvent(AuditLog.AuditAction.VERSION_AUTO_GENERATED, subject, version,
                oldSchema, newSchema, description, "system", true, true);
    }

    @Transactional
    public AuditLog logCompatibilityUpdated(String subject, String oldLevel, String newLevel, String username) {
        return logAuditEvent(AuditLog.AuditAction.COMPATIBILITY_UPDATED, subject, null,
                oldLevel, newLevel, "Compatibility level changed from " + oldLevel + " to " + newLevel,
                username, null, false);
    }

    @Transactional
    public AuditLog logSchemaDeleted(String subject, String schema, String username) {
        return logAuditEvent(AuditLog.AuditAction.DELETED, subject, null,
                schema, null, "Schema deleted", username, null, false);
    }

    @Transactional
    public AuditLog logCodeGenerated(String subject, Integer version, String language, String username) {
        return logAuditEvent(AuditLog.AuditAction.CODE_GENERATED, subject, version,
                null, language, "Generated " + language + " code", username, null, false);
    }

    @Transactional
    public AuditLog logSchemaEvolved(String subject, Integer version, String oldSchema,
                                     String newSchema, String description, boolean compatibilityPassed) {
        return logAuditEvent(AuditLog.AuditAction.SCHEMA_EVOLVED, subject, version,
                oldSchema, newSchema, description, "system", compatibilityPassed, true);
    }

    public List<AuditLog> getAuditLogsBySubject(String subject) {
        return auditLogRepository.findBySubjectOrderByCreatedAtDesc(subject);
    }

    public List<AuditLog> getAuditLogsBySubjectAndVersion(String subject, Integer version) {
        return auditLogRepository.findBySubjectAndVersionOrderByCreatedAtDesc(subject, version);
    }

    public List<AuditLog> getAuditLogsByUsername(String username) {
        return auditLogRepository.findByUsernameOrderByCreatedAtDesc(username);
    }

    public List<AuditLog> getAuditLogsByAction(AuditLog.AuditAction action) {
        return auditLogRepository.findByActionOrderByCreatedAtDesc(action);
    }

    public List<AuditLog> getRecentAuditLogs(int hours) {
        LocalDateTime since = LocalDateTime.now().minusHours(hours);
        return auditLogRepository.findByCreatedAtAfterOrderByCreatedAtDesc(since);
    }

    public List<AuditLog> getAuditLogsByDateRange(String subject, LocalDateTime start, LocalDateTime end) {
        return auditLogRepository.findBySubjectAndDateRange(subject, start, end);
    }

    public Optional<AuditLog> getAuditLogById(Long id) {
        return auditLogRepository.findById(id);
    }

    public List<AuditLog> getAllAuditLogs() {
        return auditLogRepository.findAll();
    }
}
