apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      defaultDatabase: default
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      client: standalone
    editable: true
