play.http.secret.key="changeme"

play.modules.enabled += "play.api.libs.mailer.MailerModule"

play.mailer.host="smtp.example.com"
play.mailer.port=587
play.mailer.user="your-email@example.com"
play.mailer.password="your-password"
play.mailer.from="no-reply@example.com"
play.mailer.startTLS.enable=true
play.mailer.ssl=false

play.mailer.timeout=10000
play.mailer.connectiontimeout=5000

stats {
  job {
    intervalMinutes = 5
    maxHistorySize = 100
  }
}

play.modules.disabled += "play.api.mvc.pekko.PekkoHttpServerModule"
play.modules.enabled += "play.server.netty.NettyServerModule"
