import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Grid,
  Card,
  CardContent,
  Button,
  Chip,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  LinearProgress,
  FormControlLabel,
  Switch,
  Alert,
} from '@mui/material';
import {
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Refresh as RefreshIcon,
  AutoAwesome as AutoAwesomeIcon,
  Psychology as PsychologyIcon,
} from '@mui/icons-material';
import { rootCauseRuleApi } from '../services/api';

function RootCauseRuleBase() {
  const [rules, setRules] = useState([]);
  const [statistics, setStatistics] = useState(null);
  const [loading, setLoading] = useState(true);
  const [openDialog, setOpenDialog] = useState(false);
  const [editingRule, setEditingRule] = useState(null);
  const [filter, setFilter] = useState('all');
  const [formData, setFormData] = useState({
    ruleName: '',
    ruleCode: '',
    description: '',
    rootCauseType: 'HIGH_ERROR_RATE',
    minAvailabilityThreshold: null,
    maxAvailabilityThreshold: null,
    minLatencyThreshold: null,
    maxLatencyThreshold: null,
    minErrorRateThreshold: null,
    maxErrorRateThreshold: null,
    confidenceScore: 50,
    contributingFactors: '',
    recommendations: '',
    active: true,
  });

  useEffect(() => {
    fetchData();
  }, [filter]);

  const fetchData = async () => {
    try {
      const params = {};
      if (filter === 'active') params.active = true;
      if (filter === 'auto') params.autoGenerated = true;

      const [rulesRes, statsRes] = await Promise.all([
        rootCauseRuleApi.getAll(params),
        rootCauseRuleApi.getStatistics(),
      ]);
      setRules(rulesRes.data);
      setStatistics(statsRes.data);
    } catch (error) {
      console.error('Failed to fetch data:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleMineRules = async () => {
    try {
      const result = await rootCauseRuleApi.mine();
      alert(`规则挖掘完成！新增 ${result.data.newRulesMined} 条规则，当前共 ${result.data.totalRules} 条规则`);
      fetchData();
    } catch (error) {
      console.error('Failed to mine rules:', error);
    }
  };

  const getCauseTypeColor = (type) => {
    switch (type) {
      case 'HIGH_ERROR_RATE':
        return 'error';
      case 'LATENCY_SPIKE':
        return 'warning';
      case 'TRAFFIC_SURGE':
        return 'info';
      case 'DEPENDENCY_FAILURE':
        return 'error';
      case 'RESOURCE_EXHAUSTION':
        return 'warning';
      default:
        return 'default';
    }
  };

  const getCauseTypeLabel = (type) => {
    switch (type) {
      case 'HIGH_ERROR_RATE':
        return '高错误率';
      case 'LATENCY_SPIKE':
        return '延迟突增';
      case 'TRAFFIC_SURGE':
        return '流量暴增';
      case 'DEPENDENCY_FAILURE':
        return '依赖故障';
      case 'RESOURCE_EXHAUSTION':
        return '资源耗尽';
      default:
        return type;
    }
  };

  const handleOpenCreate = () => {
    setEditingRule(null);
    setFormData({
      ruleName: '',
      ruleCode: '',
      description: '',
      rootCauseType: 'HIGH_ERROR_RATE',
      minAvailabilityThreshold: null,
      maxAvailabilityThreshold: null,
      minLatencyThreshold: null,
      maxLatencyThreshold: null,
      minErrorRateThreshold: null,
      maxErrorRateThreshold: null,
      confidenceScore: 50,
      contributingFactors: '',
      recommendations: '',
      active: true,
    });
    setOpenDialog(true);
  };

  const handleOpenEdit = (rule) => {
    setEditingRule(rule);
    setFormData({ ...rule });
    setOpenDialog(true);
  };

  const handleSave = async () => {
    try {
      if (editingRule) {
        await rootCauseRuleApi.update(editingRule.id, formData);
      } else {
        await rootCauseRuleApi.create(formData);
      }
      setOpenDialog(false);
      fetchData();
    } catch (error) {
      console.error('Failed to save rule:', error);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('确定要删除此规则吗？')) {
      try {
        await rootCauseRuleApi.delete(id);
        fetchData();
      } catch (error) {
        console.error('Failed to delete rule:', error);
      }
    }
  };

  const filteredRules = rules.filter((rule) => {
    if (filter === 'all') return true;
    if (filter === 'active') return rule.active;
    if (filter === 'auto') return rule.autoGenerated;
    if (filter === 'manual') return !rule.autoGenerated;
    return true;
  });

  if (loading) {
    return <LinearProgress />;
  }

  return (
    <Box>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h4">根因规则库</Typography>
        <Box display="flex" gap={2}>
          <Button
            variant="outlined"
            startIcon={<RefreshIcon />}
            onClick={fetchData}
          >
            刷新
          </Button>
          <Button
            variant="outlined"
            startIcon={<PsychologyIcon />}
            onClick={handleMineRules}
            color="secondary"
          >
            挖掘新规则
          </Button>
          <Button
            variant="contained"
            startIcon={<AddIcon />}
            onClick={handleOpenCreate}
          >
            新增规则
          </Button>
        </Box>
      </Box>

      <Grid container spacing={3} mb={3}>
        <Grid item xs={12} md={3}>
          <Card>
            <CardContent>
              <Typography color="textSecondary" gutterBottom>
                规则总数
              </Typography>
              <Typography variant="h3">{statistics?.totalRules || 0}</Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={3}>
          <Card>
            <CardContent>
              <Typography color="textSecondary" gutterBottom>
                活跃规则
              </Typography>
              <Typography variant="h3" color="primary">
                {statistics?.activeRules || 0}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={3}>
          <Card>
            <CardContent>
              <Typography color="textSecondary" gutterBottom>
                自动挖掘规则
              </Typography>
              <Typography variant="h3" color="secondary">
                {statistics?.autoGeneratedRules || 0}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={3}>
          <Card>
            <CardContent>
              <Typography color="textSecondary" gutterBottom>
                规则类型数
              </Typography>
              <Typography variant="h3">
                {Object.keys(statistics?.rulesByType || {}).length}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      <Box mb={2} display="flex" gap={1}>
        <Button
          variant={filter === 'all' ? 'contained' : 'outlined'}
          onClick={() => setFilter('all')}
          size="small"
        >
          全部
        </Button>
        <Button
          variant={filter === 'active' ? 'contained' : 'outlined'}
          onClick={() => setFilter('active')}
          size="small"
        >
          活跃
        </Button>
        <Button
          variant={filter === 'auto' ? 'contained' : 'outlined'}
          onClick={() => setFilter('auto')}
          size="small"
          startIcon={<AutoAwesomeIcon />}
        >
          自动挖掘
        </Button>
        <Button
          variant={filter === 'manual' ? 'contained' : 'outlined'}
          onClick={() => setFilter('manual')}
          size="small"
        >
          手动配置
        </Button>
      </Box>

      {filter === 'auto' && (
        <Alert severity="info" sx={{ mb: 2 }}>
          自动挖掘规则是系统从历史故障数据中学习生成的规则，每天凌晨2点自动执行挖掘任务。
        </Alert>
      )}

      <Card>
        <CardContent>
          <TableContainer component={Paper}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>规则名称</TableCell>
                  <TableCell>类型</TableCell>
                  <TableCell>条件</TableCell>
                  <TableCell>置信度</TableCell>
                  <TableCell>支持数/命中数</TableCell>
                  <TableCell>来源</TableCell>
                  <TableCell>状态</TableCell>
                  <TableCell>操作</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {filteredRules.map((rule) => (
                  <TableRow key={rule.id}>
                    <TableCell>
                      <Typography variant="body2" fontWeight="bold">
                        {rule.ruleName}
                      </Typography>
                      <Typography variant="caption" color="textSecondary">
                        {rule.ruleCode}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Chip
                        label={getCauseTypeLabel(rule.rootCauseType)}
                        color={getCauseTypeColor(rule.rootCauseType)}
                        size="small"
                      />
                    </TableCell>
                    <TableCell>
                      <Typography variant="caption">
                        {rule.maxAvailabilityThreshold && `可用性 < ${rule.maxAvailabilityThreshold}%\n`}
                        {rule.minLatencyThreshold && `延迟 > ${rule.minLatencyThreshold}ms\n`}
                        {rule.minErrorRateThreshold && `错误率 > ${rule.minErrorRateThreshold}%`}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Box display="flex" alignItems="center">
                        <LinearProgress
                          variant="determinate"
                          value={rule.confidenceScore}
                          sx={{ width: 60, mr: 1 }}
                        />
                        <Typography variant="body2">{rule.confidenceScore}%</Typography>
                      </Box>
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2">
                        {rule.supportCount} / {rule.hitCount}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      {rule.autoGenerated ? (
                        <Chip
                          label="自动挖掘"
                          size="small"
                          color="secondary"
                          icon={<AutoAwesomeIcon />}
                        />
                      ) : (
                        <Chip label="手动配置" size="small" />
                      )}
                    </TableCell>
                    <TableCell>
                      <Chip
                        label={rule.active ? '启用' : '禁用'}
                        size="small"
                        color={rule.active ? 'success' : 'default'}
                      />
                    </TableCell>
                    <TableCell>
                      <IconButton size="small" onClick={() => handleOpenEdit(rule)}>
                        <EditIcon />
                      </IconButton>
                      <IconButton
                        size="small"
                        onClick={() => handleDelete(rule.id)}
                        color="error"
                      >
                        <DeleteIcon />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </CardContent>
      </Card>

      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>{editingRule ? '编辑规则' : '新增规则'}</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="规则名称"
                value={formData.ruleName}
                onChange={(e) => setFormData({ ...formData, ruleName: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                label="规则代码"
                value={formData.ruleCode}
                onChange={(e) => setFormData({ ...formData, ruleCode: e.target.value })}
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="描述"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              />
            </Grid>
            <Grid item xs={12} md={4}>
              <TextField
                fullWidth
                select
                label="根因类型"
                value={formData.rootCauseType}
                onChange={(e) => setFormData({ ...formData, rootCauseType: e.target.value })}
                SelectProps={{ native: true }}
              >
                <option value="HIGH_ERROR_RATE">高错误率</option>
                <option value="LATENCY_SPIKE">延迟突增</option>
                <option value="TRAFFIC_SURGE">流量暴增</option>
                <option value="DEPENDENCY_FAILURE">依赖故障</option>
                <option value="RESOURCE_EXHAUSTION">资源耗尽</option>
                <option value="UNKNOWN">未知</option>
              </TextField>
            </Grid>
            <Grid item xs={12} md={4}>
              <TextField
                fullWidth
                type="number"
                label="置信度 (%)"
                value={formData.confidenceScore}
                onChange={(e) => setFormData({ ...formData, confidenceScore: parseInt(e.target.value) })}
                inputProps={{ min: 0, max: 100 }}
              />
            </Grid>
            <Grid item xs={12} md={4}>
              <FormControlLabel
                control={
                  <Switch
                    checked={formData.active}
                    onChange={(e) => setFormData({ ...formData, active: e.target.checked })}
                  />
                }
                label="启用规则"
              />
            </Grid>
            <Grid item xs={12}>
              <Typography variant="subtitle2" gutterBottom>
                阈值条件
              </Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                type="number"
                label="最大可用性阈值 (%)"
                value={formData.maxAvailabilityThreshold || ''}
                onChange={(e) => setFormData({ ...formData, maxAvailabilityThreshold: e.target.value ? parseFloat(e.target.value) : null })}
                inputProps={{ step: '0.01' }}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                type="number"
                label="最小延迟阈值 (ms)"
                value={formData.minLatencyThreshold || ''}
                onChange={(e) => setFormData({ ...formData, minLatencyThreshold: e.target.value ? parseFloat(e.target.value) : null })}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                type="number"
                label="最小错误率阈值 (%)"
                value={formData.minErrorRateThreshold || ''}
                onChange={(e) => setFormData({ ...formData, minErrorRateThreshold: e.target.value ? parseFloat(e.target.value) : null })}
                inputProps={{ step: '0.01' }}
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="影响因素 (用 | 分隔)"
                value={formData.contributingFactors}
                onChange={(e) => setFormData({ ...formData, contributingFactors: e.target.value })}
                placeholder="例如: 错误率高 | 可用性下降"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="建议措施 (用 | 分隔)"
                value={formData.recommendations}
                onChange={(e) => setFormData({ ...formData, recommendations: e.target.value })}
                placeholder="例如: 检查部署 | 分析日志"
                multiline
                rows={3}
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>取消</Button>
          <Button onClick={handleSave} variant="contained">
            保存
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

export default RootCauseRuleBase;
