{
 "title": "Sentinel限流监控大盘",
 "tags": [
  "sentinel",
  "rate-limit",
  "监控"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(sentinel_pass_total, service)"
   },
   {
    "name": "resource",
    "query": "label_values(sentinel_pass_total{service=~\"$service\"}, resource)"
   },
   { "name": "interval" }
  ]
 },
 "panels": [
  {
   "title": "总请求数",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sentinel_pass_total{service=~\"$service\", resource=~\"$resource\"}[$interval]))",
     "legendFormat": "Pass"
    }
   ]
  },
  {
   "title": "拦截请求数",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sentinel_block_total{service=~\"$service\", resource=~\"$resource\"}[$interval]))",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "title": "拦截率",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(sentinel_block_total{service=~\"$service\", resource=~\"$resource\"}[$interval])) / (sum(increase(sentinel_pass_total{service=~\"$service\", resource=~\"$resource\"}[$interval])) + sum(increase(sentinel_block_total{service=~\"$service\", resource=~\"$resource\"}[$interval]))) * 100",
     "legendFormat": "Block Rate"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sentinel_rt_avg{service=~\"$service\", resource=~\"$resource\"})",
     "legendFormat": "Avg RT"
    }
   ]
  },
  {
   "title": "QPS趋势 (降采样: $interval)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "QPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sentinel_pass_total{service=~\"$service\", resource=~\"$resource\"}[$interval]))",
     "legendFormat": "Pass - {{resource}}"
    },
    {
     "expr": "sum(rate(sentinel_block_total{service=~\"$service\", resource=~\"$resource\"}[$interval]))",
     "legendFormat": "Block - {{resource}}"
    }
   ]
  },
  {
   "title": "响应时间分布 (降采样: $interval)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sentinel_rt_avg{service=~\"$service\", resource=~\"$resource\"}",
     "legendFormat": "Avg RT - {{resource}}"
    }
   ]
  },
  {
   "title": "拦截请求分布 (按规则类型, 降采样: $interval)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sentinel_block_total{service=~\"$service\"}[$interval])) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "异常请求数 (降采样: $interval)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sentinel_exception_total{service=~\"$service\", resource=~\"$resource\"}[$interval]))",
     "legendFormat": "Exception - {{resource}}"
    }
   ]
  },
  {
   "title": "DC配额使用率",
   "type": "graph",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "percent", "label": "Quota Usage" }
   ],
   "targets": [
    {
     "expr": "sentinel_dc_quota_used{service=~\"$service\"} / sentinel_dc_quota_total{service=~\"$service\"} * 100",
     "legendFormat": "DC: {{dc}} - {{node}}"
    }
   ]
  },
  {
   "title": "TOP 10 拦截最多的资源",
   "type": "table",
   "gridPos": { "x": 0, "y": 28, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(increase(sentinel_block_total{service=~\"$service\"}[$interval])) by (resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "TOP 10 响应最慢的资源",
   "type": "table",
   "gridPos": { "x": 12, "y": 28, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "topk(10, sentinel_rt_avg{service=~\"$service\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}