apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: healthcheck-operator
rules:
- apiGroups:
  - health.k8s.health.checker.io
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - health.k8s.health.checker.io
  resources:
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets/eviction
  verbs:
  - create
