# Generated by Django 6.0.5 on 2026-05-12 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_vote_unique_together_vote_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': '选项', 'verbose_name_plural': '选项'},
        ),
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='choice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_choices', to=settings.AUTH_USER_MODEL, verbose_name='自定义选项创建者'),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否用户自定义'),
        ),
        migrations.AddField(
            model_name='question',
            name='allow_custom_choices',
            field=models.BooleanField(default=False, verbose_name='允许用户自定义选项'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
