const API_BASE_URL = 'http://localhost:8080/api/v1';

const request = async (url, options = {}) => {
  try {
    const response = await fetch(`${API_BASE_URL}${url}`, {
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      ...options,
    });
    return await response.json();
  } catch (error) {
    console.error('API Error:', error);
    throw error;
  }
};

export const api = {
  get: (url) => request(url),
  post: (url, data) => request(url, { method: 'POST', body: JSON.stringify(data) }),
  put: (url, data) => request(url, { method: 'PUT', body: JSON.stringify(data) }),
  delete: (url) => request(url, { method: 'DELETE' }),
};

export const mockData = {
  summary: {
    totalResources: 20,
    compliant: 8,
    nonCompliant: 12,
    complianceRate: 40,
    totalViolations: 32,
  },
  violationsByType: {
    ECS: 15,
    RDS: 8,
    OSS: 9,
  },
  violationsBySeverity: {
    high: 12,
    medium: 14,
    low: 6,
  },
  violationsByAccount: {
    'Production Account': 18,
    'Development Account': 14,
  },
  resources: [
    {
      id: 'ecs-account-prod-001-001',
      type: 'ECS',
      name: 'web-server-01',
      region: 'cn-hangzhou',
      tags: { Environment: 'Production', Department: 'Engineering', CostCenter: 'CC001' },
      status: 'Running',
      createdAt: '2024-02-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'ecs-account-prod-001-002',
      type: 'ECS',
      name: 'database-server',
      region: 'cn-hangzhou',
      tags: { Environment: 'Production', Department: 'Data' },
      status: 'Running',
      createdAt: '2023-11-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'ecs-account-prod-001-003',
      type: 'ECS',
      name: 'dev-server-01',
      region: 'cn-hangzhou',
      tags: { env: 'dev', team: 'backend' },
      status: 'Stopped',
      createdAt: '2024-04-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'ecs-account-prod-001-004',
      type: 'ECS',
      name: 'untagged-server',
      region: 'cn-hangzhou',
      tags: {},
      status: 'Running',
      createdAt: '2024-05-14T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'rds-account-prod-001-001',
      type: 'RDS',
      name: 'prod-mysql',
      region: 'cn-hangzhou',
      tags: { Environment: 'Production', Department: 'Data', CostCenter: 'CC002' },
      status: 'Running',
      createdAt: '2024-01-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'rds-account-prod-001-002',
      type: 'RDS',
      name: 'test-postgres',
      region: 'cn-hangzhou',
      tags: { Environment: 'Testing' },
      status: 'Running',
      createdAt: '2024-03-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'rds-account-prod-001-003',
      type: 'RDS',
      name: 'legacy-oracle',
      region: 'cn-hangzhou',
      tags: { Owner: 'admin' },
      status: 'Running',
      createdAt: '2023-05-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'oss-account-prod-001-001',
      type: 'OSS',
      name: 'prod-backup-bucket',
      region: 'cn-hangzhou',
      tags: { Environment: 'Production', Department: 'Engineering', CostCenter: 'CC001' },
      status: 'Active',
      createdAt: '2023-12-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'oss-account-prod-001-002',
      type: 'OSS',
      name: 'dev-assets',
      region: 'cn-hangzhou',
      tags: { Environment: 'Development', Department: 'Engineering' },
      status: 'Active',
      createdAt: '2024-04-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'oss-account-prod-001-003',
      type: 'OSS',
      name: 'public-static',
      region: 'cn-hangzhou',
      tags: {},
      status: 'Active',
      createdAt: '2023-09-29T00:00:00Z',
      accountId: 'account-prod-001',
      accountName: 'Production Account',
    },
    {
      id: 'ecs-account-dev-001-001',
      type: 'ECS',
      name: 'dev-web-01',
      region: 'cn-beijing',
      tags: { Environment: 'Development', Department: 'Engineering' },
      status: 'Running',
      createdAt: '2024-03-15T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'ecs-account-dev-001-002',
      type: 'ECS',
      name: 'test-api-01',
      region: 'cn-beijing',
      tags: {},
      status: 'Stopped',
      createdAt: '2024-04-01T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'ecs-account-dev-001-003',
      type: 'ECS',
      name: 'ci-runner-01',
      region: 'cn-beijing',
      tags: { Environment: 'Testing', Department: 'Engineering' },
      status: 'Running',
      createdAt: '2024-02-20T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'ecs-account-dev-001-004',
      type: 'ECS',
      name: 'staging-app',
      region: 'cn-beijing',
      tags: { env: 'staging' },
      status: 'Running',
      createdAt: '2024-05-01T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'rds-account-dev-001-001',
      type: 'RDS',
      name: 'dev-mysql',
      region: 'cn-beijing',
      tags: { Environment: 'Development', Department: 'Data', CostCenter: 'CC003' },
      status: 'Running',
      createdAt: '2024-01-10T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'rds-account-dev-001-002',
      type: 'RDS',
      name: 'test-redis',
      region: 'cn-beijing',
      tags: { Owner: 'dev-team' },
      status: 'Running',
      createdAt: '2024-03-05T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'rds-account-dev-001-003',
      type: 'RDS',
      name: 'staging-postgres',
      region: 'cn-beijing',
      tags: { Environment: 'Staging' },
      status: 'Running',
      createdAt: '2024-04-15T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'oss-account-dev-001-001',
      type: 'OSS',
      name: 'dev-build-artifacts',
      region: 'cn-beijing',
      tags: { Environment: 'Development', Department: 'Engineering', CostCenter: 'CC003' },
      status: 'Active',
      createdAt: '2024-02-01T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'oss-account-dev-001-002',
      type: 'OSS',
      name: 'test-logs',
      region: 'cn-beijing',
      tags: { Environment: 'Testing' },
      status: 'Active',
      createdAt: '2024-03-20T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
    {
      id: 'oss-account-dev-001-003',
      type: 'OSS',
      name: 'shared-docs',
      region: 'cn-beijing',
      tags: {},
      status: 'Active',
      createdAt: '2023-12-01T00:00:00Z',
      accountId: 'account-dev-001',
      accountName: 'Development Account',
    },
  ],
  rules: [
    {
      id: 'required-environment',
      name: 'Required Environment Tag',
      type: 'required_tag',
      description: 'All resources must have an Environment tag',
      key: 'Environment',
      severity: 'high',
      enabled: true,
      values: ['Production', 'Development', 'Testing', 'Staging'],
    },
    {
      id: 'required-department',
      name: 'Required Department Tag',
      type: 'required_tag',
      description: 'All resources must have a Department tag',
      key: 'Department',
      severity: 'medium',
      enabled: true,
      values: ['Engineering', 'Data', 'Marketing', 'Finance', 'Operations'],
    },
    {
      id: 'required-costcenter',
      name: 'Required CostCenter Tag',
      type: 'required_tag',
      description: 'Production resources must have a CostCenter tag',
      key: 'CostCenter',
      severity: 'high',
      enabled: true,
    },
    {
      id: 'environment-values',
      name: 'Environment Tag Allowed Values',
      type: 'tag_value_in_list',
      description: 'Environment tag must be one of the allowed values',
      key: 'Environment',
      severity: 'medium',
      enabled: true,
      values: ['Production', 'Development', 'Testing', 'Staging'],
    },
    {
      id: 'costcenter-format',
      name: 'CostCenter Format Check',
      type: 'tag_value_regex',
      description: 'CostCenter must match pattern CC followed by numbers (e.g., CC001)',
      key: 'CostCenter',
      value: '^CC\\d{3}$',
      severity: 'medium',
      enabled: true,
    },
    {
      id: 'case-sensitive-environment',
      name: 'Environment Tag Case Sensitivity',
      type: 'case_sensitive',
      description: 'Environment tag key must be properly cased',
      key: 'Environment',
      severity: 'low',
      enabled: true,
    },
    {
      id: 'forbidden-owner-tag',
      name: 'Forbidden Owner Tag',
      type: 'forbidden_tag',
      description: 'Owner tag is deprecated, use Department instead',
      key: 'Owner',
      severity: 'low',
      enabled: true,
    },
  ],
  accounts: [
    { id: 'account-prod-001', name: 'Production Account' },
    { id: 'account-dev-001', name: 'Development Account' },
  ],
};
