package metrics

import (
	"context"
	"encoding/json"
	"net/http"
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/sirupsen/logrus"

	"github.com/security/container-escape-detector/pkg/types"
)

type Exporter struct {
	registry *prometheus.Registry
	logger   *logrus.Logger
	server   *http.Server
	metrics  *DetectorMetrics
	mu       sync.RWMutex
}

type DetectorMetrics struct {
	EventsTotal        *prometheus.CounterVec
	AlertsTotal        *prometheus.CounterVec
	ContainerRiskScore *prometheus.GaugeVec
	ContainerRiskLevel *prometheus.GaugeVec
	AttackChainsTotal  *prometheus.CounterVec
	BPFEventLatency    prometheus.Histogram
	RuleEvaluations    *prometheus.CounterVec
	CapUsage           *prometheus.CounterVec
	MountEvents        *prometheus.CounterVec
	SuspiciousProcess  *prometheus.CounterVec
	MonitoredContainers *prometheus.GaugeVec
	EscapeAttempts     *prometheus.CounterVec
}

func NewExporter(logger *logrus.Logger) *Exporter {
	reg := prometheus.NewRegistry()

	return &Exporter{
		registry: reg,
		logger:   logger,
		metrics:  initMetrics(reg),
	}
}

func initMetrics(reg *prometheus.Registry) *DetectorMetrics {
	factory := promauto.With(reg)

	return &DetectorMetrics{
		EventsTotal: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "events_total",
				Help:      "Total number of events processed by type",
			},
			[]string{"event_type", "container_id", "container_name"},
		),

		AlertsTotal: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "alerts_total",
				Help:      "Total number of alerts generated by severity",
			},
			[]string{"severity", "rule_id", "container_id", "container_name"},
		),

		ContainerRiskScore: factory.NewGaugeVec(
			prometheus.GaugeOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "container_risk_score",
				Help:      "Current risk score for each container (0-100)",
			},
			[]string{"container_id", "container_name"},
		),

		ContainerRiskLevel: factory.NewGaugeVec(
			prometheus.GaugeOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "container_risk_level",
				Help:      "Risk level for each container (0=INFO, 1=LOW, 2=MEDIUM, 3=HIGH, 4=CRITICAL)",
			},
			[]string{"container_id", "container_name"},
		),

		AttackChainsTotal: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "attack_chains_total",
				Help:      "Total number of attack chains detected",
			},
			[]string{"attack_type", "container_id", "container_name"},
		),

		BPFEventLatency: factory.NewHistogram(
			prometheus.HistogramOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "bpf_event_latency_seconds",
				Help:      "Latency of BPF event processing",
				Buckets:   prometheus.ExponentialBuckets(1e-6, 10, 6),
			},
		),

		RuleEvaluations: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "rule_evaluations_total",
				Help:      "Total rule evaluations by result",
			},
			[]string{"rule_id", "result"},
		),

		CapUsage: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "capability_usage_total",
				Help:      "Total capability checks by capability name",
			},
			[]string{"capability", "container_id", "container_name"},
		),

		MountEvents: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "mount_events_total",
				Help:      "Total mount events by suspicious flag",
			},
			[]string{"suspicious", "container_id", "container_name"},
		),

		SuspiciousProcess: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "suspicious_processes_total",
				Help:      "Total suspicious processes detected",
			},
			[]string{"container_id", "container_name"},
		),

		MonitoredContainers: factory.NewGaugeVec(
			prometheus.GaugeOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "monitored_containers",
				Help:      "Number of containers currently monitored",
			},
			[]string{},
		),

		EscapeAttempts: factory.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: "container_escape",
				Subsystem: "detector",
				Name:      "escape_attempts_total",
				Help:      "Total container escape attempts detected",
			},
			[]string{"attack_type", "container_id", "container_name", "severity"},
		),
	}
}

func (e *Exporter) Start(address string) error {
	mux := http.NewServeMux()

	mux.Handle("/metrics", promhttp.HandlerFor(e.registry, promhttp.HandlerOpts{}))
	mux.HandleFunc("/health", e.healthHandler)
	mux.HandleFunc("/alerts", e.alertsHandler)
	mux.HandleFunc("/risk", e.riskHandler)

	e.server = &http.Server{
		Addr:         address,
		Handler:      mux,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	go func() {
		e.logger.Infof("Prometheus metrics server starting on %s", address)
		if err := e.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			e.logger.Errorf("Metrics server error: %v", err)
		}
	}()

	return nil
}

func (e *Exporter) RecordEvent(event *types.BPFEvent, container *types.ContainerInfo) {
	containerID := ""
	containerName := ""
	if container != nil {
		containerID = container.ID[:12]
		containerName = container.Name
	}

	e.metrics.EventsTotal.WithLabelValues(
		string(event.EventType), containerID, containerName).Inc()

	if event.EventType == types.EventCapability && event.CapName != "" {
		e.metrics.CapUsage.WithLabelValues(
			event.CapName, containerID, containerName).Inc()
	}

	latency := time.Since(event.Timestamp)
	e.metrics.BPFEventLatency.Observe(float64(latency.Seconds()))
}

func (e *Exporter) RecordMountEvent(suspicious bool, container *types.ContainerInfo) {
	containerID := ""
	containerName := ""
	if container != nil {
		containerID = container.ID[:12]
		containerName = container.Name
	}

	suspiciousStr := "false"
	if suspicious {
		suspiciousStr = "true"
	}

	e.metrics.MountEvents.WithLabelValues(suspiciousStr, containerID, containerName).Inc()
}

func (e *Exporter) RecordAlert(alert *types.Alert) {
	containerID := ""
	containerName := ""
	if alert.ContainerID != "" {
		containerID = alert.ContainerID[:12]
		containerName = alert.ContainerName
	}

	e.metrics.AlertsTotal.WithLabelValues(
		string(alert.Severity), alert.RuleID, containerID, containerName).Inc()
}

func (e *Exporter) RecordRuleEvaluation(ruleID string, matched bool) {
	result := "no_match"
	if matched {
		result = "matched"
	}
	e.metrics.RuleEvaluations.WithLabelValues(ruleID, result).Inc()
}

func (e *Exporter) RecordContainerRisk(container *types.ContainerInfo, score float64, level types.RiskLevel) {
	if container == nil {
		return
	}

	containerID := container.ID[:12]
	containerName := container.Name

	e.metrics.ContainerRiskScore.WithLabelValues(containerID, containerName).Set(score)
	e.metrics.ContainerRiskLevel.WithLabelValues(containerID, containerName).Set(riskLevelToFloat(level))
}

func (e *Exporter) RecordSuspiciousProcess(container *types.ContainerInfo) {
	containerID := ""
	containerName := ""
	if container != nil {
		containerID = container.ID[:12]
		containerName = container.Name
	}

	e.metrics.SuspiciousProcess.WithLabelValues(containerID, containerName).Inc()
}

func (e *Exporter) RecordAttackChain(chain *types.AttackChain, container *types.ContainerInfo) {
	containerID := ""
	containerName := ""
	if container != nil {
		containerID = container.ID[:12]
		containerName = container.Name
	}

	e.metrics.AttackChainsTotal.WithLabelValues(
		chain.Description, containerID, containerName).Inc()

	var severity types.RiskLevel
	switch {
	case chain.TotalScore >= 80:
		severity = types.RiskCritical
	case chain.TotalScore >= 50:
		severity = types.RiskHigh
	case chain.TotalScore >= 25:
		severity = types.RiskMedium
	default:
		severity = types.RiskLow
	}

	e.metrics.EscapeAttempts.WithLabelValues(
		chain.Description, containerID, containerName, string(severity)).Inc()
}

func (e *Exporter) SetMonitoredContainers(count int) {
	e.metrics.MonitoredContainers.WithLabelValues().Set(float64(count))
}

func (e *Exporter) healthHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

var currentAlerts []types.Alert
var currentRisk map[string]*types.RiskAssessment

func (e *Exporter) UpdateAlerts(alerts []types.Alert) {
	e.mu.Lock()
	defer e.mu.Unlock()
	currentAlerts = alerts
}

func (e *Exporter) UpdateRiskAssessments(assessments map[string]*types.RiskAssessment) {
	e.mu.Lock()
	defer e.mu.Unlock()
	currentRisk = assessments
}

func (e *Exporter) alertsHandler(w http.ResponseWriter, r *http.Request) {
	e.mu.RLock()
	defer e.mu.RUnlock()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(currentAlerts)
}

func (e *Exporter) riskHandler(w http.ResponseWriter, r *http.Request) {
	e.mu.RLock()
	defer e.mu.RUnlock()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(currentRisk)
}

func (e *Exporter) Close() error {
	if e.server != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		return e.server.Shutdown(ctx)
	}
	return nil
}

func riskLevelToFloat(level types.RiskLevel) float64 {
	switch level {
	case types.RiskInfo:
		return 0
	case types.RiskLow:
		return 1
	case types.RiskMedium:
		return 2
	case types.RiskHigh:
		return 3
	case types.RiskCritical:
		return 4
	default:
		return 0
	}
}
