package com.sla.monitor.repository;

import com.sla.monitor.model.RootCauseAnalysis;
import com.sla.monitor.model.RootCauseRule;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface RootCauseRuleRepository extends JpaRepository<RootCauseRule, Long> {

    Optional<RootCauseRule> findByRuleCode(String ruleCode);

    List<RootCauseRule> findByActiveTrue();

    List<RootCauseRule> findByActiveTrueOrderByConfidenceScoreDesc();

    List<RootCauseRule> findByRootCauseTypeAndActiveTrue(
            RootCauseAnalysis.RootCauseCategory rootCauseType);

    @Query("SELECT r FROM RootCauseRule r WHERE r.active = true " +
           "AND (:availability IS NULL OR " +
           "(:availability BETWEEN COALESCE(r.minAvailabilityThreshold, 0) AND COALESCE(r.maxAvailabilityThreshold, 100))) " +
           "AND (:latency IS NULL OR " +
           "(:latency >= COALESCE(r.minLatencyThreshold, 0) AND :latency <= COALESCE(r.maxLatencyThreshold, 999999))) " +
           "AND (:errorRate IS NULL OR " +
           "(:errorRate >= COALESCE(r.minErrorRateThreshold, 0) AND :errorRate <= COALESCE(r.maxErrorRateThreshold, 100))) " +
           "ORDER BY r.confidenceScore DESC")
    List<RootCauseRule> findMatchingRules(
            @Param("availability") Double availability,
            @Param("latency") Double latency,
            @Param("errorRate") Double errorRate);

    @Query("SELECT r FROM RootCauseRule r WHERE r.active = true AND r.autoGenerated = true " +
           "ORDER BY r.supportCount DESC")
    List<RootCauseRule> findAutoGeneratedRules();

    boolean existsByRuleCode(String ruleCode);

    @Query("SELECT r.rootCauseType, COUNT(r) FROM RootCauseRule r " +
           "WHERE r.active = true GROUP BY r.rootCauseType")
    List<Object[]> countRulesByType();
}
