export interface SymbolItem {
  label: string;
  latex: string;
  display: string;
}

export interface SymbolCategory {
  id: string;
  name: string;
  symbols: SymbolItem[];
}

export const symbolCategories: SymbolCategory[] = [
  {
    id: 'basic',
    name: '基础',
    symbols: [
      { label: '分数', latex: '\\frac{}{}', display: 'a/b' },
      { label: '根号', latex: '\\sqrt{}', display: '√' },
      { label: 'n次根号', latex: '\\sqrt[]{}', display: 'ⁿ√' },
      { label: '上标', latex: '^{}', display: 'xⁿ' },
      { label: '下标', latex: '_{}', display: 'xₙ' },
      { label: '上 下标', latex: '_{}^{}', display: 'xₙⁿ' },
      { label: '括号', latex: '\\left( \\right)', display: '( )' },
      { label: '方括号', latex: '\\left[ \\right]', display: '[ ]' },
      { label: '花括号', latex: '\\left\\{ \\right\\}', display: '{ }' },
      { label: '绝对值', latex: '\\left| \\right|', display: '| |' },
      { label: '点', latex: '\\cdot', display: '·' },
      { label: '乘', latex: '\\times', display: '×' },
      { label: '除', latex: '\\div', display: '÷' },
      { label: '正负', latex: '\\pm', display: '±' },
      { label: '干', latex: '\\mp', display: '∓' },
      { label: '不等', latex: '\\neq', display: '≠' },
      { label: '约等', latex: '\\approx', display: '≈' },
      { label: '小于等于', latex: '\\leq', display: '≤' },
      { label: '大于等于', latex: '\\geq', display: '≥' },
      { label: '无穷', latex: '\\infty', display: '∞' },
      { label: '偏导', latex: '\\partial', display: '∂' },
      { label: '省略', latex: '\\cdots', display: '⋯' },
      { label: '竖省略', latex: '\\vdots', display: '⋮' },
      { label: '对角省略', latex: '\\ddots', display: '⋱' },
    ],
  },
  {
    id: 'greek',
    name: '希腊字母',
    symbols: [
      { label: 'alpha', latex: '\\alpha', display: 'α' },
      { label: 'beta', latex: '\\beta', display: 'β' },
      { label: 'gamma', latex: '\\gamma', display: 'γ' },
      { label: 'delta', latex: '\\delta', display: 'δ' },
      { label: 'epsilon', latex: '\\epsilon', display: 'ε' },
      { label: 'zeta', latex: '\\zeta', display: 'ζ' },
      { label: 'eta', latex: '\\eta', display: 'η' },
      { label: 'theta', latex: '\\theta', display: 'θ' },
      { label: 'iota', latex: '\\iota', display: 'ι' },
      { label: 'kappa', latex: '\\kappa', display: 'κ' },
      { label: 'lambda', latex: '\\lambda', display: 'λ' },
      { label: 'mu', latex: '\\mu', display: 'μ' },
      { label: 'nu', latex: '\\nu', display: 'ν' },
      { label: 'xi', latex: '\\xi', display: 'ξ' },
      { label: 'pi', latex: '\\pi', display: 'π' },
      { label: 'rho', latex: '\\rho', display: 'ρ' },
      { label: 'sigma', latex: '\\sigma', display: 'σ' },
      { label: 'tau', latex: '\\tau', display: 'τ' },
      { label: 'upsilon', latex: '\\upsilon', display: 'υ' },
      { label: 'phi', latex: '\\phi', display: 'φ' },
      { label: 'chi', latex: '\\chi', display: 'χ' },
      { label: 'psi', latex: '\\psi', display: 'ψ' },
      { label: 'omega', latex: '\\omega', display: 'ω' },
      { label: 'Gamma', latex: '\\Gamma', display: 'Γ' },
      { label: 'Delta', latex: '\\Delta', display: 'Δ' },
      { label: 'Theta', latex: '\\Theta', display: 'Θ' },
      { label: 'Lambda', latex: '\\Lambda', display: 'Λ' },
      { label: 'Xi', latex: '\\Xi', display: 'Ξ' },
      { label: 'Pi', latex: '\\Pi', display: 'Π' },
      { label: 'Sigma', latex: '\\Sigma', display: 'Σ' },
      { label: 'Phi', latex: '\\Phi', display: 'Φ' },
      { label: 'Psi', latex: '\\Psi', display: 'Ψ' },
      { label: 'Omega', latex: '\\Omega', display: 'Ω' },
    ],
  },
  {
    id: 'operators',
    name: '运算',
    symbols: [
      { label: '求和', latex: '\\sum_{}^{}', display: '∑' },
      { label: '求积', latex: '\\prod_{}^{}', display: '∏' },
      { label: '积分', latex: '\\int_{}^{}', display: '∫' },
      { label: '二重积分', latex: '\\iint_{}^{}', display: '∬' },
      { label: '三重积分', latex: '\\iiint_{}^{}', display: '∭' },
      { label: '线积分', latex: '\\oint_{}^{}', display: '∮' },
      { label: '极限', latex: '\\lim_{}', display: 'lim' },
      { label: '导数', latex: '\\frac{d}{dx}', display: "d/dx" },
      { label: '偏导数', latex: '\\frac{\\partial}{\\partial x}', display: '∂/∂x' },
      { label: '梯度', latex: '\\nabla', display: '∇' },
      { label: 'sin', latex: '\\sin', display: 'sin' },
      { label: 'cos', latex: '\\cos', display: 'cos' },
      { label: 'tan', latex: '\\tan', display: 'tan' },
      { label: 'log', latex: '\\log', display: 'log' },
      { label: 'ln', latex: '\\ln', display: 'ln' },
      { label: 'exp', latex: '\\exp', display: 'exp' },
      { label: 'max', latex: '\\max', display: 'max' },
      { label: 'min', latex: '\\min', display: 'min' },
      { label: 'sup', latex: '\\sup', display: 'sup' },
      { label: 'inf', latex: '\\inf', display: 'inf' },
      { label: 'det', latex: '\\det', display: 'det' },
      { label: 'dim', latex: '\\dim', display: 'dim' },
      { label: 'ker', latex: '\\ker', display: 'ker' },
      { label: 'deg', latex: '\\deg', display: 'deg' },
    ],
  },
  {
    id: 'arrows',
    name: '箭头',
    symbols: [
      { label: '右箭头', latex: '\\rightarrow', display: '→' },
      { label: '左箭头', latex: '\\leftarrow', display: '←' },
      { label: '双向箭头', latex: '\\leftrightarrow', display: '↔' },
      { label: '长右箭头', latex: '\\longrightarrow', display: '⟶' },
      { label: '长左箭头', latex: '\\longleftarrow', display: '⟵' },
      { label: '推出', latex: '\\Rightarrow', display: '⇒' },
      { label: '逆推', latex: '\\Leftarrow', display: '⇐' },
      { label: '等价', latex: '\\Leftrightarrow', display: '⇔' },
      { label: '上映射', latex: '\\uparrow', display: '↑' },
      { label: '下映射', latex: '\\downarrow', display: '↓' },
      { label: '映射', latex: '\\mapsto', display: '↦' },
      { label: '长映射', latex: '\\longmapsto', display: '⟼' },
      { label: '钩右箭头', latex: '\\hookrightarrow', display: '↪' },
      { label: '双线右箭头', latex: '\\rightrightarrows', display: '⇉' },
    ],
  },
  {
    id: 'matrix',
    name: '矩阵',
    symbols: [
      { label: '2×2矩阵', latex: '\\begin{pmatrix}  &  \\\\  &  \\end{pmatrix}', display: '[2×2]' },
      { label: '3×3矩阵', latex: '\\begin{pmatrix}  &  &  \\\\  &  &  \\\\  &  &  \\end{pmatrix}', display: '[3×3]' },
      { label: '2×2行列式', latex: '\\begin{vmatrix}  &  \\\\  &  \\end{vmatrix}', display: '|2×2|' },
      { label: '3×3行列式', latex: '\\begin{vmatrix}  &  &  \\\\  &  &  \\\\  &  &  \\end{vmatrix}', display: '|3×3|' },
      { label: '2×2方括号矩阵', latex: '\\begin{bmatrix}  &  \\\\  &  \\end{bmatrix}', display: '[2×2]' },
      { label: '3×3方括号矩阵', latex: '\\begin{bmatrix}  &  &  \\\\  &  &  \\\\  &  &  \\end{bmatrix}', display: '[3×3]' },
      { label: '省略矩阵', latex: '\\begin{pmatrix} a_{11} & \\cdots & a_{1n} \\\\ \\vdots & \\ddots & \\vdots \\\\ a_{m1} & \\cdots & a_{mn} \\end{pmatrix}', display: '[…]' },
      { label: '分段函数', latex: '\\begin{cases}  &  \\\\  &  \\end{cases}', display: '{f}' },
      { label: '增广矩阵', latex: '\\left[\\begin{array}{cc|c}  &  &  \\\\  &  &  \\end{array}\\right]', display: '[aug]' },
    ],
  },
  {
    id: 'sets',
    name: '集合',
    symbols: [
      { label: '属于', latex: '\\in', display: '∈' },
      { label: '不属于', latex: '\\notin', display: '∉' },
      { label: '子集', latex: '\\subset', display: '⊂' },
      { label: '真子集', latex: '\\subseteq', display: '⊆' },
      { label: '超集', latex: '\\supset', display: '⊃' },
      { label: '真超集', latex: '\\supseteq', display: '⊇' },
      { label: '并集', latex: '\\cup', display: '∪' },
      { label: '交集', latex: '\\cap', display: '∩' },
      { label: '空集', latex: '\\emptyset', display: '∅' },
      { label: '实数集', latex: '\\mathbb{R}', display: 'ℝ' },
      { label: '整数集', latex: '\\mathbb{Z}', display: 'ℤ' },
      { label: '自然数集', latex: '\\mathbb{N}', display: 'ℕ' },
      { label: '有理数集', latex: '\\mathbb{Q}', display: 'ℚ' },
      { label: '复数集', latex: '\\mathbb{C}', display: 'ℂ' },
      { label: '任意', latex: '\\forall', display: '∀' },
      { label: '存在', latex: '\\exists', display: '∃' },
      { label: '非', latex: '\\neg', display: '¬' },
      { label: '且', latex: '\\land', display: '∧' },
      { label: '或', latex: '\\lor', display: '∨' },
      { label: '推出', latex: '\\implies', display: '⟹' },
      { label: '等价', latex: '\\iff', display: '⟺' },
    ],
  },
];
