package com.sla.monitor.service;

import com.sla.monitor.dto.RootCauseResultDTO;
import com.sla.monitor.model.RootCauseAnalysis;
import com.sla.monitor.model.RootCauseRule;
import com.sla.monitor.model.SlaMetrics;
import com.sla.monitor.repository.RootCauseAnalysisRepository;
import com.sla.monitor.repository.SlaMetricsRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class RootCauseAnalysisService {

    private static final Logger logger = LoggerFactory.getLogger(RootCauseAnalysisService.class);

    private final SlaMetricsRepository slaMetricsRepository;
    private final RootCauseAnalysisRepository analysisRepository;
    private final RootCauseRuleMiningService ruleMiningService;

    public RootCauseAnalysisService(SlaMetricsRepository slaMetricsRepository,
                                     RootCauseAnalysisRepository analysisRepository,
                                     RootCauseRuleMiningService ruleMiningService) {
        this.slaMetricsRepository = slaMetricsRepository;
        this.analysisRepository = analysisRepository;
        this.ruleMiningService = ruleMiningService;
    }

    public RootCauseResultDTO performRootCauseAnalysis(String serviceName) {
        LocalDateTime startTime = LocalDateTime.now().minusHours(1);
        List<SlaMetrics> recentMetrics = slaMetricsRepository
                .findByServiceNameAndTimestampAfterOrderByTimestampAsc(serviceName, startTime);

        RootCauseResultDTO result = new RootCauseResultDTO();
        result.setServiceName(serviceName);
        result.setTimestamp(LocalDateTime.now());
        result.setContributingFactors(new ArrayList<>());
        result.setRecommendations(new ArrayList<>());

        if (recentMetrics.isEmpty()) {
            result.setPrimaryCause("INSUFFICIENT_DATA");
            result.setConfidenceScore(0.0);
            result.getContributingFactors().add("No metrics data available for analysis");
            return result;
        }

        SlaMetrics latest = recentMetrics.get(recentMetrics.size() - 1);

        List<RootCauseRule> matchedRules = ruleMiningService.matchRules(
                latest.getAvailability(),
                latest.getAvgLatencyMs(),
                latest.getErrorRate()
        );

        if (!matchedRules.isEmpty()) {
            result = buildResultFromRules(serviceName, latest, matchedRules);
        } else {
            result = buildResultFromHeuristics(serviceName, latest, recentMetrics);
        }

        saveAnalysis(serviceName, result);
        updateRuleSupportCounts(serviceName, result);

        return result;
    }

    private RootCauseResultDTO buildResultFromRules(String serviceName, SlaMetrics latest,
                                                     List<RootCauseRule> matchedRules) {
        RootCauseResultDTO result = new RootCauseResultDTO();
        result.setServiceName(serviceName);
        result.setTimestamp(LocalDateTime.now());
        result.setContributingFactors(new ArrayList<>());
        result.setRecommendations(new ArrayList<>());

        RootCauseRule topRule = matchedRules.get(0);
        result.setPrimaryCause(topRule.getRootCauseType().name());
        result.setConfidenceScore(topRule.getConfidenceScore() / 100.0);

        Set<String> factors = new LinkedHashSet<>();
        Set<String> recommendations = new LinkedHashSet<>();

        for (RootCauseRule rule : matchedRules) {
            if (rule.getContributingFactors() != null) {
                factors.addAll(Arrays.asList(rule.getContributingFactors().split(" \\| ")));
            }
            if (rule.getRecommendations() != null) {
                recommendations.addAll(Arrays.asList(rule.getRecommendations().split(" \\| ")));
            }
        }

        factors.add("Matched " + matchedRules.size() + " rule(s) from rule base");
        factors.add("Top rule: " + topRule.getRuleName() +
                " (confidence: " + topRule.getConfidenceScore() + "%)");

        if (topRule.isAutoGenerated()) {
            factors.add("Rule auto-mined from historical data with support: " +
                    topRule.getSupportCount() + " occurrences");
        }

        result.getContributingFactors().addAll(factors);
        result.getRecommendations().addAll(recommendations);

        return result;
    }

    private RootCauseResultDTO buildResultFromHeuristics(String serviceName, SlaMetrics latest,
                                                          List<SlaMetrics> recentMetrics) {
        RootCauseResultDTO result = new RootCauseResultDTO();
        result.setServiceName(serviceName);
        result.setTimestamp(LocalDateTime.now());
        result.setContributingFactors(new ArrayList<>());
        result.setRecommendations(new ArrayList<>());

        List<String> factors = new ArrayList<>();
        List<String> recommendations = new ArrayList<>();
        double confidenceScore = 0.0;
        RootCauseAnalysis.RootCauseCategory primaryCause = RootCauseAnalysis.RootCauseCategory.UNKNOWN;

        double errorRateDeviation = latest.getErrorRate();
        double latencyDeviation = latest.getAvgLatencyMs();

        if (errorRateDeviation > 5.0) {
            primaryCause = RootCauseAnalysis.RootCauseCategory.HIGH_ERROR_RATE;
            confidenceScore = calculateConfidence(recentMetrics, "errorRate");
            factors.add("High error rate detected: " + String.format("%.2f", errorRateDeviation) + "%");
            factors.add("Availability impact: " + String.format("%.2f", latest.getAvailability()) + "%");
            recommendations.add("Check recent deployments for bugs");
            recommendations.add("Review error logs for exception patterns");
            recommendations.add("Verify downstream service health");
        } else if (latencyDeviation > 1000) {
            primaryCause = RootCauseAnalysis.RootCauseCategory.LATENCY_SPIKE;
            confidenceScore = calculateConfidence(recentMetrics, "latency");
            factors.add("Latency spike detected: P95=" + String.format("%.0f", latest.getP95LatencyMs()) + "ms");
            factors.add("Average latency: " + String.format("%.0f", latest.getAvgLatencyMs()) + "ms");
            recommendations.add("Check database query performance");
            recommendations.add("Review recent code changes for performance issues");
            recommendations.add("Consider scaling resources");
        }

        long requestCountIncrease = detectTrafficIncrease(recentMetrics);
        if (requestCountIncrease > 50) {
            if (primaryCause == RootCauseAnalysis.RootCauseCategory.UNKNOWN) {
                primaryCause = RootCauseAnalysis.RootCauseCategory.TRAFFIC_SURGE;
                confidenceScore = 0.7;
            }
            factors.add("Traffic increased by " + requestCountIncrease + "% in the last hour");
            recommendations.add("Consider auto-scaling to handle increased load");
            recommendations.add("Check for potential DDoS or bot traffic");
        }

        factors.add("Analysis based on heuristic rules (no matching learned rules)");

        result.setPrimaryCause(primaryCause.name());
        result.setConfidenceScore(confidenceScore);
        result.setContributingFactors(factors);
        result.setRecommendations(recommendations);

        return result;
    }

    private void updateRuleSupportCounts(String serviceName, RootCauseResultDTO result) {
        try {
            RootCauseAnalysis.RootCauseCategory cause =
                    RootCauseAnalysis.RootCauseCategory.valueOf(result.getPrimaryCause());

            List<RootCauseAnalysis> recentAnalyses = analysisRepository
                    .findByServiceNameAndTimestampAfterOrderByTimestampDesc(
                            serviceName, LocalDateTime.now().minusHours(24));

            long sameCauseCount = recentAnalyses.stream()
                    .filter(a -> a.getPrimaryCause() == cause)
                    .count();

            if (sameCauseCount >= 3) {
                logger.debug("Root cause {} has occurred {} times today for service {}",
                        cause, sameCauseCount, serviceName);
            }
        } catch (Exception e) {
            logger.debug("Could not update rule support counts", e);
        }
    }

    private double calculateConfidence(List<SlaMetrics> metrics, String metricType) {
        if (metrics.size() < 10) {
            return 0.6;
        }

        int count = 0;
        int violationCount = 0;

        for (SlaMetrics metric : metrics) {
            count++;
            boolean violated = switch (metricType) {
                case "errorRate" -> metric.getErrorRate() > 2.0;
                case "latency" -> metric.getAvgLatencyMs() > 500;
                default -> metric.getAvailability() < 99.9;
            };
            if (violated) violationCount++;
        }

        return (double) violationCount / count;
    }

    private long detectTrafficIncrease(List<SlaMetrics> metrics) {
        if (metrics.size() < 10) {
            return 0;
        }

        int midPoint = metrics.size() / 2;
        long firstHalfRequests = metrics.subList(0, midPoint).stream()
                .mapToLong(SlaMetrics::getTotalRequests)
                .sum();
        long secondHalfRequests = metrics.subList(midPoint, metrics.size()).stream()
                .mapToLong(SlaMetrics::getTotalRequests)
                .sum();

        if (firstHalfRequests == 0) {
            return secondHalfRequests > 0 ? 100 : 0;
        }

        return ((secondHalfRequests - firstHalfRequests) * 100) / firstHalfRequests;
    }

    private void saveAnalysis(String serviceName, RootCauseResultDTO result) {
        try {
            RootCauseAnalysis analysis = new RootCauseAnalysis();
            analysis.setServiceName(serviceName);
            analysis.setTimestamp(result.getTimestamp());
            analysis.setPrimaryCause(RootCauseAnalysis.RootCauseCategory.valueOf(result.getPrimaryCause()));
            analysis.setConfidenceScore(result.getConfidenceScore());
            analysis.setContributingFactors(String.join(" | ", result.getContributingFactors()));
            analysis.setRecommendations(String.join(" | ", result.getRecommendations()));
            analysis.setAnalysisResult("Primary cause: " + result.getPrimaryCause() + 
                    " with confidence: " + result.getConfidenceScore());
            
            analysisRepository.save(analysis);
        } catch (Exception e) {
            logger.error("Failed to save root cause analysis", e);
        }
    }

    public List<RootCauseAnalysis> getAnalysisHistory(String serviceName, int hours) {
        return analysisRepository.findByServiceNameAndTimestampAfterOrderByTimestampDesc(
                serviceName, LocalDateTime.now().minusHours(hours));
    }
}
