import os


ES_HOSTS = os.getenv("ES_HOSTS", "http://localhost:9200").split(",")
ES_USERNAME = os.getenv("ES_USERNAME", "elastic")
ES_PASSWORD = os.getenv("ES_PASSWORD", "changeme")
ES_TIMEOUT = int(os.getenv("ES_TIMEOUT", "30"))

FLASK_HOST = os.getenv("FLASK_HOST", "0.0.0.0")
FLASK_PORT = int(os.getenv("FLASK_PORT", "5000"))
FLASK_DEBUG = os.getenv("FLASK_DEBUG", "false").lower() == "true"

PROMETHEUS_PORT = int(os.getenv("PROMETHEUS_PORT", "9091"))

AUDIT_LOG_DIR = os.getenv("AUDIT_LOG_DIR", "./audit_logs")
AUDIT_LOG_MAX_BYTES = int(os.getenv("AUDIT_LOG_MAX_BYTES", str(10 * 1024 * 1024)))
AUDIT_LOG_BACKUP_COUNT = int(os.getenv("AUDIT_LOG_BACKUP_COUNT", "10"))

AUDIT_ENABLE_ES_INDEX = os.getenv("AUDIT_ENABLE_ES_INDEX", "true").lower() == "true"
AUDIT_ES_INDEX_PREFIX = os.getenv("AUDIT_ES_INDEX_PREFIX", "ilm_audit-")
AUDIT_ES_INDEX_DATE_FORMAT = os.getenv("AUDIT_ES_INDEX_DATE_FORMAT", "%Y.%m.%d")
AUDIT_ES_BATCH_SIZE = int(os.getenv("AUDIT_ES_BATCH_SIZE", "100"))
AUDIT_ES_FLUSH_INTERVAL = int(os.getenv("AUDIT_ES_FLUSH_INTERVAL", "5"))

SCHEDULER_INTERVAL_SECONDS = int(os.getenv("SCHEDULER_INTERVAL_SECONDS", "60"))

ROLLOVER_MAX_SIZE_GB = float(os.getenv("ROLLOVER_MAX_SIZE_GB", "50"))
ROLLOVER_MAX_DOCS = int(os.getenv("ROLLOVER_MAX_DOCS", "1000000000"))
ROLLOVER_MAX_AGE_DAYS = int(os.getenv("ROLLOVER_MAX_AGE_DAYS", "30"))

FREEZE_AGE_DAYS = int(os.getenv("FREEZE_AGE_DAYS", "90"))
DELETE_AGE_DAYS = int(os.getenv("DELETE_AGE_DAYS", "365"))

HOT_TIER_NODE_ATTR = os.getenv("HOT_TIER_NODE_ATTR", "data_hot")
WARM_TIER_NODE_ATTR = os.getenv("WARM_TIER_NODE_ATTR", "data_warm")
COLD_TIER_NODE_ATTR = os.getenv("COLD_TIER_NODE_ATTR", "data_cold")

MIGRATE_TO_WARM_AGE_DAYS = int(os.getenv("MIGRATE_TO_WARM_AGE_DAYS", "30"))
MIGRATE_TO_COLD_AGE_DAYS = int(os.getenv("MIGRATE_TO_COLD_AGE_DAYS", "90"))

DISK_WATERMARK_LOW_PERCENT = float(os.getenv("DISK_WATERMARK_LOW_PERCENT", "85.0"))
DISK_WATERMARK_HIGH_PERCENT = float(os.getenv("DISK_WATERMARK_HIGH_PERCENT", "90.0"))
DISK_WATERMARK_FLOOD_STAGE_PERCENT = float(os.getenv("DISK_WATERMARK_FLOOD_STAGE_PERCENT", "95.0"))
DISK_CHECK_INTERVAL_SECONDS = int(os.getenv("DISK_CHECK_INTERVAL_SECONDS", "30"))
DISK_WAIT_MAX_RETRIES = int(os.getenv("DISK_WAIT_MAX_RETRIES", "10"))
DISK_WAIT_BACKOFF_SECONDS = int(os.getenv("DISK_WAIT_BACKOFF_SECONDS", "60"))

PERF_ANALYSIS_TOP_N = int(os.getenv("PERF_ANALYSIS_TOP_N", "10"))
PERF_SLOW_QUERY_THRESHOLD_MS = int(os.getenv("PERF_SLOW_QUERY_THRESHOLD_MS", "5000"))
PERF_SLOW_SHARD_THRESHOLD_MS = int(os.getenv("PERF_SLOW_SHARD_THRESHOLD_MS", "2000"))

COST_HOT_GB_PER_MONTH = float(os.getenv("COST_HOT_GB_PER_MONTH", "0.10"))
COST_WARM_GB_PER_MONTH = float(os.getenv("COST_WARM_GB_PER_MONTH", "0.06"))
COST_COLD_GB_PER_MONTH = float(os.getenv("COST_COLD_GB_PER_MONTH", "0.03"))
COST_FROZEN_GB_PER_MONTH = float(os.getenv("COST_FROZEN_GB_PER_MONTH", "0.015"))
COST_REPLICAS_MULTIPLIER = float(os.getenv("COST_REPLICAS_MULTIPLIER", "1.0"))
COST_CURRENCY = os.getenv("COST_CURRENCY", "USD")

REBUILD_ENABLE_AUTO = os.getenv("REBUILD_ENABLE_AUTO", "true").lower() == "true"
REBUILD_FRAGMENTATION_THRESHOLD = float(os.getenv("REBUILD_FRAGMENTATION_THRESHOLD", "30.0"))
REBUILD_MIN_AGE_DAYS = int(os.getenv("REBUILD_MIN_AGE_DAYS", "7"))
REBUILD_MIN_SIZE_GB = float(os.getenv("REBUILD_MIN_SIZE_GB", "1.0"))
REBUILD_MAX_CONCURRENT = int(os.getenv("REBUILD_MAX_CONCURRENT", "2"))
REBUILD_INTERVAL_SECONDS = int(os.getenv("REBUILD_INTERVAL_SECONDS", "3600"))
REBUILD_READ_TIMEOUT = os.getenv("REBUILD_READ_TIMEOUT", "5m")
REBUILD_SLICES = int(os.getenv("REBUILD_SLICES", "auto"))
REBUILD_MAX_RETRIES = int(os.getenv("REBUILD_MAX_RETRIES", "3"))

CCR_ENABLED = os.getenv("CCR_ENABLED", "false").lower() == "true"
CCR_REMOTE_CLUSTER_NAME = os.getenv("CCR_REMOTE_CLUSTER_NAME", "dr-cluster")
CCR_REMOTE_HOSTS = os.getenv("CCR_REMOTE_HOSTS", "http://dr-cluster:9200").split(",")
CCR_REMOTE_USERNAME = os.getenv("CCR_REMOTE_USERNAME", "elastic")
CCR_REMOTE_PASSWORD = os.getenv("CCR_REMOTE_PASSWORD", "changeme")
CCR_SYNC_HOT_ONLY = os.getenv("CCR_SYNC_HOT_ONLY", "true").lower() == "true"
CCR_MAX_CONCURRENT_FOLLOWERS = int(os.getenv("CCR_MAX_CONCURRENT_FOLLOWERS", "5"))
CCR_REPLICATION_TYPE = os.getenv("CCR_REPLICATION_TYPE", "follower")
CCR_AUTO_FOLLOW_PATTERN = os.getenv("CCR_AUTO_FOLLOW_PATTERN", "logs-*,metrics-*")
CCR_REMOTE_POLL_INTERVAL = os.getenv("CCR_REMOTE_POLL_INTERVAL", "10s")
CCR_REMOTE_MAX_READ_REQUEST_SIZE = os.getenv("CCR_REMOTE_MAX_READ_REQUEST_SIZE", "128mb")
CCR_REMOTE_MAX_OUTSTANDING_READ_REQUESTS = int(os.getenv("CCR_REMOTE_MAX_OUTSTANDING_READ_REQUESTS", "3"))
CCR_REMOTE_MAX_OUTSTANDING_WRITES = int(os.getenv("CCR_REMOTE_MAX_OUTSTANDING_WRITES", "2"))
