package com.sla.monitor.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "root_cause_rules")
public class RootCauseRule {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String ruleName;

    @Column(nullable = false)
    private String ruleCode;

    @Lob
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RootCauseAnalysis.RootCauseCategory rootCauseType;

    private Double minAvailabilityThreshold;
    private Double maxAvailabilityThreshold;
    private Double minLatencyThreshold;
    private Double maxLatencyThreshold;
    private Double minErrorRateThreshold;
    private Double maxErrorRateThreshold;
    private Double minRequestCountIncrease;

    @Lob
    private String conditionExpression;

    @Lob
    private String contributingFactors;

    @Lob
    private String recommendations;

    @Column(nullable = false)
    private Integer confidenceScore;

    private Integer supportCount;

    private Integer hitCount;

    private Double precision;

    private Double recall;

    private boolean autoGenerated = false;

    private boolean active = true;

    private LocalDateTime lastVerifiedAt;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (confidenceScore == null) {
            confidenceScore = 50;
        }
        if (supportCount == null) {
            supportCount = 0;
        }
        if (hitCount == null) {
            hitCount = 0;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public void incrementHitCount() {
        this.hitCount = (this.hitCount == null ? 0 : this.hitCount) + 1;
    }

    public void incrementSupportCount() {
        this.supportCount = (this.supportCount == null ? 0 : this.supportCount) + 1;
    }

    public void updatePrecision() {
        if (hitCount != null && hitCount > 0) {
            this.precision = (double) supportCount / hitCount;
        }
    }
}
