import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

print("=" * 60)
print("知识图谱问答系统 - 演示脚本")
print("=" * 60)
print("\n项目结构完整，包含以下模块：")
print("\n1. config/ - 配置模块")
print("   - settings.py: 系统配置")
print("\n2. kg/ - 知识图谱模块")
print("   - schema.py: 实体和关系模式定义")
print("   - neo4j_client.py: Neo4j数据库客户端")
print("   - data_init.py: 知识图谱数据初始化")
print("\n3. nlp/ - 自然语言处理模块")
print("   - intent_classifier.py: BERT和规则意图分类器")
print("   - entity_extractor.py: 实体提取器")
print("\n4. query/ - 查询处理模块")
print("   - cypher_generator.py: Cypher查询生成器")
print("   - answer_processor.py: 答案处理器（含溯源）")
print("\n5. services/ - 服务层")
print("   - qa_service.py: 问答服务")
print("\n6. api/ - API层")
print("   - main.py: FastAPI接口")
print("\n7. tests/ - 测试模块")
print("   - test_qa.py: 问答测试")

print("\n" + "=" * 60)
print("核心功能：")
print("=" * 60)
print("✓ 领域知识图谱构建 (疾病、症状、药物、科室、医生等8类实体)")
print("✓ 8种关系类型 (有症状、使用药物、属于科室等)")
print("✓ BERT意图识别 (支持11种查询意图)")
print("✓ 自然语言到Cypher查询转换")
print("✓ 多跳推理 (支持可变跳数查询)")
print("✓ 模糊匹配 (实体模糊搜索)")
print("✓ 答案溯源 (推理路径和证据链)")
print("✓ FastAPI RESTful接口")

print("\n" + "=" * 60)
print("使用步骤：")
print("=" * 60)
print("1. 安装依赖: pip install -r requirements.txt")
print("2. 配置Neo4j连接: 复制.env.example为.env并修改")
print("3. 初始化知识图谱: python -m kg.data_init")
print("4. 启动API服务: python main.py")
print("5. 访问文档: http://localhost:8000/docs")

print("\n" + "=" * 60)
print("示例问题：")
print("=" * 60)
print("• 感冒有什么症状？")
print("• 感冒吃什么药？")
print("• 阿莫西林治什么病？")
print("• 呼吸内科看什么病？")
print("• 张医生治什么病？")
print("• 感冒有什么症状然后用什么药？ (多跳)")
print("• 关于感冒的信息 (模糊)")
