// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && amd64 && !android
// +build linux,amd64,!android

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type escapeDetectObjects struct {
	TracepointSysEnterMount     *ebpf.Program `ebpf:"tracepoint_sys_enter_mount"`
	TracepointSysExitMount      *ebpf.Program `ebpf:"tracepoint_sys_exit_mount"`
	TracepointSysEnterUmount2   *ebpf.Program `ebpf:"tracepoint_sys_enter_umount2"`
	TracepointSysEnterChroot    *ebpf.Program `ebpf:"tracepoint_sys_enter_chroot"`
	TracepointSysEnterPivotRoot *ebpf.Program `ebpf:"tracepoint_sys_enter_pivot_root"`
	TracepointSysEnterSetns     *ebpf.Program `ebpf:"tracepoint_sys_enter_setns"`
	TracepointSysEnterUnshare   *ebpf.Program `ebpf:"tracepoint_sys_enter_unshare"`
	TracepointSysEnterPtrace    *ebpf.Program `ebpf:"tracepoint_sys_enter_ptrace"`
	TracepointSysEnterInitModule   *ebpf.Program `ebpf:"tracepoint_sys_enter_init_module"`
	TracepointSysEnterDeleteModule *ebpf.Program `ebpf:"tracepoint_sys_enter_delete_module"`
	TracepointSysEnterExecve    *ebpf.Program `ebpf:"tracepoint_sys_enter_execve"`
	TracepointSysEnterOpenat    *ebpf.Program `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysEnterMknod     *ebpf.Program `ebpf:"tracepoint_sys_enter_mknod"`
	KprobeCapCapable            *ebpf.Program `ebpf:"kprobe_cap_capable"`
	KprobeCommitCreds           *ebpf.Program `ebpf:"kprobe_commit_creds"`
	Events                      *ebpf.Map     `ebpf:"events"`
	PidToPidns                  *ebpf.Map     `ebpf:"pid_to_pidns"`
	PidToMntns                  *ebpf.Map     `ebpf:"pid_to_mntns"`
}

func (o *escapeDetectObjects) Close() error {
	return closeAll(
		o.TracepointSysEnterMount,
		o.TracepointSysExitMount,
		o.TracepointSysEnterUmount2,
		o.TracepointSysEnterChroot,
		o.TracepointSysEnterPivotRoot,
		o.TracepointSysEnterSetns,
		o.TracepointSysEnterUnshare,
		o.TracepointSysEnterPtrace,
		o.TracepointSysEnterInitModule,
		o.TracepointSysEnterDeleteModule,
		o.TracepointSysEnterExecve,
		o.TracepointSysEnterOpenat,
		o.TracepointSysEnterMknod,
		o.KprobeCapCapable,
		o.KprobeCommitCreds,
		o.Events,
		o.PidToPidns,
		o.PidToMntns,
	)
}

func loadEscapeDetect() (*ebpf.CollectionSpec, error) {
	spec := &ebpf.CollectionSpec{
		Maps: map[string]*ebpf.MapSpec{
			"events": {
				Name:       "events",
				Type:       ebpf.PerfEventArray,
				KeySize:    4,
				ValueSize:  4,
				MaxEntries: 1024,
			},
			"pid_to_pidns": {
				Name:       "pid_to_pidns",
				Type:       ebpf.Hash,
				KeySize:    4,
				ValueSize:  8,
				MaxEntries: 10240,
			},
			"pid_to_mntns": {
				Name:       "pid_to_mntns",
				Type:       ebpf.Hash,
				KeySize:    4,
				ValueSize:  8,
				MaxEntries: 10240,
			},
		},
		Programs: map[string]*ebpf.ProgramSpec{
			"tracepoint_sys_enter_mount": {
				Name: "tracepoint_sys_enter_mount",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_exit_mount": {
				Name: "tracepoint_sys_exit_mount",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_umount2": {
				Name: "tracepoint_sys_enter_umount2",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_chroot": {
				Name: "tracepoint_sys_enter_chroot",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_pivot_root": {
				Name: "tracepoint_sys_enter_pivot_root",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_setns": {
				Name: "tracepoint_sys_enter_setns",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_unshare": {
				Name: "tracepoint_sys_enter_unshare",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_ptrace": {
				Name: "tracepoint_sys_enter_ptrace",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_init_module": {
				Name: "tracepoint_sys_enter_init_module",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_delete_module": {
				Name: "tracepoint_sys_enter_delete_module",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_execve": {
				Name: "tracepoint_sys_enter_execve",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_openat": {
				Name: "tracepoint_sys_enter_openat",
				Type: ebpf.TracePoint,
			},
			"tracepoint_sys_enter_mknod": {
				Name: "tracepoint_sys_enter_mknod",
				Type: ebpf.TracePoint,
			},
			"kprobe_cap_capable": {
				Name: "kprobe_cap_capable",
				Type: ebpf.Kprobe,
			},
			"kprobe_commit_creds": {
				Name: "kprobe_commit_creds",
				Type: ebpf.Kprobe,
			},
		},
	}
	return spec, nil
}

func closeAll(closers ...io.Closer) error {
	var errs []error
	for _, c := range closers {
		if c == nil {
			continue
		}
		if err := c.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("error closing objects: %v", errs)
	}
	return nil
}

func mustReader(data []byte) io.ReaderAt {
	return bytes.NewReader(data)
}
