package com.schemaregistry.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "audit_logs")
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "subject", nullable = false)
    private String subject;

    @Column(name = "version")
    private Integer version;

    @Enumerated(EnumType.STRING)
    @Column(name = "action", nullable = false)
    private AuditAction action;

    @Column(name = "username")
    private String username;

    @Column(name = "old_schema_text", columnDefinition = "TEXT")
    private String oldSchemaText;

    @Column(name = "new_schema_text", columnDefinition = "TEXT")
    private String newSchemaText;

    @Column(name = "change_description")
    private String changeDescription;

    @Column(name = "compatibility_check_passed")
    private Boolean compatibilityCheckPassed;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    public enum AuditAction {
        CREATED,
        VERSION_ADDED,
        VERSION_AUTO_GENERATED,
        COMPATIBILITY_UPDATED,
        DELETED,
        CODE_GENERATED,
        SCHEMA_EVOLVED
    }
}
