global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'distributed-id-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'distid-service'
    dns_sd_configs:
      - names:
          - 'distid-service'
        type: 'A'
        port: 8080
        refresh_interval: 10s
