import type {
  DashboardStats,
  Repository,
  Dependency,
  VersionConflict,
  Vulnerability,
  UpgradeSuggestion,
  ScanResult,
  BatchPRResponse,
} from '@/types';

export const mockRepositories: Repository[] = [
  {
    id: 1,
    name: 'user-service',
    fullName: 'myorg/user-service',
    htmlUrl: 'https://github.com/myorg/user-service',
    defaultBranch: 'main',
    buildTool: 'MAVEN',
    lastScanTime: '2026-05-29T10:30:00',
    scanStatus: 'COMPLETED',
    healthScore: 72.5,
  },
  {
    id: 2,
    name: 'order-service',
    fullName: 'myorg/order-service',
    htmlUrl: 'https://github.com/myorg/order-service',
    defaultBranch: 'main',
    buildTool: 'MAVEN',
    lastScanTime: '2026-05-28T14:20:00',
    scanStatus: 'COMPLETED',
    healthScore: 58.0,
  },
  {
    id: 3,
    name: 'payment-gateway',
    fullName: 'myorg/payment-gateway',
    htmlUrl: 'https://github.com/myorg/payment-gateway',
    defaultBranch: 'develop',
    buildTool: 'GRADLE',
    lastScanTime: '2026-05-29T16:45:00',
    scanStatus: 'COMPLETED',
    healthScore: 85.0,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalServices: 3,
  totalDependencies: 42,
  conflictCount: 5,
  vulnerabilityCount: 5,
  outdatedCount: 8,
  healthScore: 71.8,
  recentScans: [
    { repoName: 'user-service', time: '2026-05-29T10:30:00', status: 'COMPLETED', findings: 6 },
    { repoName: 'order-service', time: '2026-05-28T14:20:00', status: 'COMPLETED', findings: 7 },
    { repoName: 'payment-gateway', time: '2026-05-29T16:45:00', status: 'COMPLETED', findings: 3 },
  ],
  topVulnerabilities: [
    {
      cveId: 'CVE-2023-44487',
      severity: 'CRITICAL',
      cvssScore: 9.8,
      description: 'HTTP/2 Rapid Reset Attack vulnerability in Spring Boot web framework',
      affectedVersions: '3.0.9',
      fixedVersion: '3.1.0',
      publishedDate: '2024-01-15T00:00:00',
      affectedServices: [
        { repoId: 2, repoName: 'order-service', dependency: 'org.springframework.boot:spring-boot-starter-web', version: '3.0.9' },
      ],
    },
    {
      cveId: 'CVE-2024-0001',
      severity: 'HIGH',
      cvssScore: 7.5,
      description: 'SQL Injection vulnerability in Spring Data JPA when using native queries with parameter binding',
      affectedVersions: '3.1.5',
      fixedVersion: '3.2.0',
      publishedDate: '2024-02-20T00:00:00',
      affectedServices: [
        { repoId: 1, repoName: 'user-service', dependency: 'org.springframework.boot:spring-boot-starter-data-jpa', version: '3.1.5' },
      ],
    },
    {
      cveId: 'CVE-2024-0003',
      severity: 'HIGH',
      cvssScore: 7.8,
      description: 'Path traversal vulnerability in Spring MVC static resource handling',
      affectedVersions: '3.0.9',
      fixedVersion: '3.1.2',
      publishedDate: '2024-03-10T00:00:00',
      affectedServices: [
        { repoId: 2, repoName: 'order-service', dependency: 'org.springframework.boot:spring-boot-starter-web', version: '3.0.9' },
      ],
    },
  ],
};

export const mockDependencies: Dependency[] = [
  {
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-web',
    version: '3.1.5',
    latestVersion: '3.2.5',
    scope: 'compile',
    isOutdated: true,
    isDirect: true,
    transitiveDependencies: [
      {
        groupId: 'org.springframework',
        artifactId: 'spring-webmvc',
        version: '6.0.13',
        latestVersion: '6.1.6',
        scope: 'compile',
        isOutdated: true,
        isDirect: false,
        transitiveDependencies: [],
      },
      {
        groupId: 'org.apache.tomcat.embed',
        artifactId: 'tomcat-embed-core',
        version: '10.1.15',
        latestVersion: '10.1.20',
        scope: 'compile',
        isOutdated: true,
        isDirect: false,
        transitiveDependencies: [],
      },
    ],
  },
  {
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-data-jpa',
    version: '3.1.5',
    latestVersion: '3.2.5',
    scope: 'compile',
    isOutdated: true,
    isDirect: true,
    transitiveDependencies: [],
  },
  {
    groupId: 'com.google.guava',
    artifactId: 'guava',
    version: '32.1.2-jre',
    latestVersion: '33.0.0-jre',
    scope: 'compile',
    isOutdated: true,
    isDirect: true,
    transitiveDependencies: [],
  },
  {
    groupId: 'org.postgresql',
    artifactId: 'postgresql',
    version: '42.6.0',
    latestVersion: '42.7.3',
    scope: 'runtime',
    isOutdated: false,
    isDirect: true,
    transitiveDependencies: [],
  },
  {
    groupId: 'com.fasterxml.jackson.core',
    artifactId: 'jackson-databind',
    version: '2.15.2',
    latestVersion: '2.17.0',
    scope: 'compile',
    isOutdated: true,
    isDirect: false,
    transitiveDependencies: [],
  },
];

export const mockConflicts: VersionConflict[] = [
  {
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-web',
    versions: [
      { service: 'user-service', version: '3.1.5' },
      { service: 'order-service', version: '3.0.9' },
      { service: 'payment-gateway', version: '3.2.4' },
    ],
    recommendedVersion: '3.2.5',
    severity: 'HIGH',
  },
  {
    groupId: 'com.google.guava',
    artifactId: 'guava',
    versions: [
      { service: 'user-service', version: '32.1.2-jre' },
      { service: 'order-service', version: '31.1-jre' },
    ],
    recommendedVersion: '33.0.0-jre',
    severity: 'MEDIUM',
  },
];

export const mockVulnerabilities: Vulnerability[] = [
  {
    cveId: 'CVE-2023-44487',
    severity: 'CRITICAL',
    cvssScore: 9.8,
    description: 'HTTP/2 Rapid Reset Attack vulnerability in Spring Boot web framework',
    affectedVersions: '3.0.9',
    fixedVersion: '3.1.0',
    publishedDate: '2024-01-15T00:00:00',
    affectedServices: [
      { repoId: 2, repoName: 'order-service', dependency: 'org.springframework.boot:spring-boot-starter-web', version: '3.0.9' },
    ],
  },
  {
    cveId: 'CVE-2024-0001',
    severity: 'HIGH',
    cvssScore: 7.5,
    description: 'SQL Injection vulnerability in Spring Data JPA when using native queries with parameter binding',
    affectedVersions: '3.1.5',
    fixedVersion: '3.2.0',
    publishedDate: '2024-02-20T00:00:00',
    affectedServices: [
      { repoId: 1, repoName: 'user-service', dependency: 'org.springframework.boot:spring-boot-starter-data-jpa', version: '3.1.5' },
    ],
  },
  {
    cveId: 'CVE-2024-0003',
    severity: 'HIGH',
    cvssScore: 7.8,
    description: 'Path traversal vulnerability in Spring MVC static resource handling',
    affectedVersions: '3.0.9',
    fixedVersion: '3.1.2',
    publishedDate: '2024-03-10T00:00:00',
    affectedServices: [
      { repoId: 2, repoName: 'order-service', dependency: 'org.springframework.boot:spring-boot-starter-web', version: '3.0.9' },
    ],
  },
  {
    cveId: 'CVE-2024-0002',
    severity: 'MEDIUM',
    cvssScore: 5.3,
    description: 'Denial of Service in Jackson Databind deserialization of deeply nested JSON',
    affectedVersions: '2.15.2',
    fixedVersion: '2.16.0',
    publishedDate: '2024-02-05T00:00:00',
    affectedServices: [
      { repoId: 1, repoName: 'user-service', dependency: 'com.fasterxml.jackson.core:jackson-databind', version: '2.15.2' },
    ],
  },
  {
    cveId: 'CVE-2024-0004',
    severity: 'LOW',
    cvssScore: 3.1,
    description: 'Information disclosure in Guava cache statistics exposed via JMX',
    affectedVersions: '31.1-jre',
    fixedVersion: '32.0.0-jre',
    publishedDate: '2024-01-28T00:00:00',
    affectedServices: [
      { repoId: 2, repoName: 'order-service', dependency: 'com.google.guava:guava', version: '31.1-jre' },
    ],
  },
];

export const mockUpgrades: UpgradeSuggestion[] = [
  {
    id: 1,
    repoId: 1,
    repoName: 'user-service',
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-web',
    currentVersion: '3.1.5',
    targetVersion: '3.2.5',
    upgradeType: 'MINOR',
    riskLevel: 'LOW_RISK',
    compatibilityScore: 85.0,
    breakingChanges: [],
    releaseNotes: 'Minor version upgrade with new features including improved HTTP/2 support, better observability, and performance optimizations.',
    selected: false,
  },
  {
    id: 2,
    repoId: 1,
    repoName: 'user-service',
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-data-jpa',
    currentVersion: '3.1.5',
    targetVersion: '3.2.5',
    upgradeType: 'MINOR',
    riskLevel: 'LOW_RISK',
    compatibilityScore: 85.0,
    breakingChanges: [],
    releaseNotes: 'New query derivation features and improved transaction management. Fully backward compatible.',
    selected: false,
  },
  {
    id: 3,
    repoId: 1,
    repoName: 'user-service',
    groupId: 'com.google.guava',
    artifactId: 'guava',
    currentVersion: '32.1.2-jre',
    targetVersion: '33.0.0-jre',
    upgradeType: 'MAJOR',
    riskLevel: 'MEDIUM_RISK',
    compatibilityScore: 55.0,
    breakingChanges: [
      'Removed deprecated CacheBuilder methods',
      'FluentIterable class removed',
      'Minimum Java version raised to 11',
    ],
    releaseNotes: 'Major release with significant API changes. Review migration guide before upgrading.',
    selected: false,
  },
  {
    id: 4,
    repoId: 1,
    repoName: 'user-service',
    groupId: 'com.fasterxml.jackson.core',
    artifactId: 'jackson-databind',
    currentVersion: '2.15.2',
    targetVersion: '2.17.0',
    upgradeType: 'MINOR',
    riskLevel: 'MEDIUM_RISK',
    compatibilityScore: 70.0,
    breakingChanges: [
      'Serialization behavior for null values changed',
      'Java 8 date/time format changes',
    ],
    releaseNotes: 'Performance improvements and security fixes. Check serialization outputs.',
    selected: false,
  },
  {
    id: 5,
    repoId: 2,
    repoName: 'order-service',
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-web',
    currentVersion: '3.0.9',
    targetVersion: '3.2.5',
    upgradeType: 'MINOR',
    riskLevel: 'MEDIUM_RISK',
    compatibilityScore: 65.0,
    breakingChanges: [
      'Some property default values changed',
      'Actuator endpoints renamed',
    ],
    releaseNotes: 'Security critical upgrade fixing CVE-2023-44487 HTTP/2 Rapid Reset vulnerability.',
    selected: false,
  },
  {
    id: 6,
    repoId: 2,
    repoName: 'order-service',
    groupId: 'org.springframework.boot',
    artifactId: 'spring-boot-starter-data-jpa',
    currentVersion: '3.0.9',
    targetVersion: '3.2.5',
    upgradeType: 'MINOR',
    riskLevel: 'MEDIUM_RISK',
    compatibilityScore: 65.0,
    breakingChanges: [
      'Query generation changes',
    ],
    releaseNotes: 'Multiple security fixes and performance improvements.',
    selected: false,
  },
  {
    id: 7,
    repoId: 2,
    repoName: 'order-service',
    groupId: 'com.google.guava',
    artifactId: 'guava',
    currentVersion: '31.1-jre',
    targetVersion: '33.0.0-jre',
    upgradeType: 'MAJOR',
    riskLevel: 'HIGH_RISK',
    compatibilityScore: 40.0,
    breakingChanges: [
      'Removed deprecated CacheBuilder methods',
      'FluentIterable class removed',
      'Minimum Java version raised to 11',
      'Many Guava 22-31 deprecated APIs removed',
    ],
    releaseNotes: 'Major version upgrade with extensive breaking changes. Requires thorough testing.',
    selected: false,
  },
  {
    id: 8,
    repoId: 2,
    repoName: 'order-service',
    groupId: 'org.apache.commons',
    artifactId: 'commons-lang3',
    currentVersion: '3.12.0',
    targetVersion: '3.14.0',
    upgradeType: 'MINOR',
    riskLevel: 'SAFE',
    compatibilityScore: 92.0,
    breakingChanges: [],
    releaseNotes: 'Pure bug fixes and new utility methods. 100% backward compatible.',
    selected: false,
  },
];

export const mockScanHistory: ScanResult[] = [
  { id: 1, repoId: 1, scanTime: '2026-05-29T10:30:00', status: 'COMPLETED', totalDeps: 28, conflictCount: 1, vulnerabilityCount: 2, outdatedCount: 3 },
  { id: 2, repoId: 1, scanTime: '2026-05-27T09:15:00', status: 'COMPLETED', totalDeps: 27, conflictCount: 1, vulnerabilityCount: 2, outdatedCount: 2 },
  { id: 3, repoId: 1, scanTime: '2026-05-25T16:40:00', status: 'COMPLETED', totalDeps: 27, conflictCount: 2, vulnerabilityCount: 1, outdatedCount: 3 },
];

export const mockBatchPRResponse: BatchPRResponse = {
  pullRequestUrl: 'https://github.com/myorg/order-service/pull/123',
  pullRequestNumber: 123,
  branchName: 'deps-upgrade-20260530',
  modifiedFiles: ['pom.xml'],
};
