import { create } from 'zustand';
import type {
  DataStore,
  ColumnInfo,
  AnalysisResult,
  AnalysisMethod,
  UploadResponse,
} from '../../shared/types';

export const useDataStore = create<DataStore>((set) => ({
  fileId: null,
  columns: [],
  data: [],
  stats: null,
  columnInfo: [],
  treatment: null,
  outcome: null,
  covariates: [],
  method: 'psm',
  timeVariable: null,
  result: null,
  isLoading: false,
  error: null,

  setFileId: (fileId: string | null) => set({ fileId }),
  setColumns: (columns: string[]) => set({ columns }),
  setData: (data: Record<string, any>[]) => set({ data }),
  setStats: (stats: UploadResponse['stats'] | null) => set({ stats }),
  setColumnInfo: (columnInfo: ColumnInfo[]) => set({ columnInfo }),
  setTreatment: (treatment: string | null) => set({ treatment }),
  setOutcome: (outcome: string | null) => set({ outcome }),
  setCovariates: (covariates: string[]) => set({ covariates }),
  setMethod: (method: AnalysisMethod) => set({ method }),
  setTimeVariable: (timeVariable: string | null) => set({ timeVariable }),
  setResult: (result: AnalysisResult | null) => set({ result }),
  setIsLoading: (isLoading: boolean) => set({ isLoading }),
  setError: (error: string | null) => set({ error }),
  resetData: () => set({
    fileId: null,
    columns: [],
    data: [],
    stats: null,
    columnInfo: [],
    treatment: null,
    outcome: null,
    covariates: [],
    method: 'psm',
    timeVariable: null,
    result: null,
    isLoading: false,
    error: null,
  }),
}));
